In [60]:
import numpy as np
import pandas as pd

In [61]:
#Series from Lists

In [62]:
#String
Country=['bangladesh','slilanka','napal','pakisrtan']
pd.Series(Country)

0    bangladesh
1      slilanka
2         napal
3     pakisrtan
dtype: str

In [63]:
#integer
runs=[33,44,5,56,77,88]
runs_set=pd.Series(runs)

In [64]:
#custom index
marks=[55,66,77]
Subject=['english','math','bangla']
pd.Series(marks,index=Subject)

english    55
math       66
bangla     77
dtype: int64

In [65]:
pd.Series(marks,index=Subject,name="nadia marks")

english    55
math       66
bangla     77
Name: nadia marks, dtype: int64

In [66]:
#Series from dic
marks={
    'maths':44,
    'English':55,
    'science':88
    
}
marks_Serice=pd.Series(marks,name='nadia jahan')
marks_Serice

maths      44
English    55
science    88
Name: nadia jahan, dtype: int64

In [67]:
#Serice Attibutes
[]#Size
marks_Serice.size

3

In [68]:
[]#Dtype
marks_Serice.dtype

dtype('int64')

In [69]:
[]#Name
marks_Serice.name

'nadia jahan'

In [70]:
#is unique
marks_Serice.is_unique

True

In [71]:
#index
runs_set.index

RangeIndex(start=0, stop=6, step=1)

In [72]:
#values

type(marks_Serice.values)

numpy.ndarray

In [73]:
#Series using Read_Csv
[]#With one col
df=pd.read_csv('D:\practics with camplxe\insurance (1).csv')
s=df.squeeze()
s=df['age']
s

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [74]:
type(s)

pandas.Series

In [75]:
[]# With 2 cols
df=pd.read_csv('D:\practics with camplxe\insurance (1).csv',index_col='sex')
s=df.squeeze()
s=df['age']
print(s)

sex
female    19
male      18
male      28
male      33
male      32
          ..
male      50
female    18
female    18
female    21
female    61
Name: age, Length: 1338, dtype: int64

# Series mathod

[]#head and tail

In [76]:
s.head()
#print frist 5 row in col
s.tail()
s

sex
female    19
male      18
male      28
male      33
male      32
          ..
male      50
female    18
female    18
female    21
female    61
Name: age, Length: 1338, dtype: int64

In [77]:
[]#sample
s.sample()

sex
female    19
Name: age, dtype: int64

#values_counts-> movies

In [78]:
s.value_counts()

age
18    69
19    68
46    29
52    29
48    29
20    29
45    29
47    29
51    29
50    29
28    28
25    28
23    28
27    28
22    28
26    28
24    28
21    28
53    28
54    28
49    28
31    27
30    27
41    27
40    27
43    27
44    27
29    27
42    27
33    26
32    26
56    26
34    26
55    26
57    26
37    25
59    25
35    25
38    25
36    25
58    25
39    25
60    23
62    23
63    23
61    23
64    22
Name: count, dtype: int64

In [79]:
  #sort values-> inplace
#s.sort_values(ascending=True).head().values[0]#True(0-1-2)#false(2-1-0)
s.sort_values(inplace=True)
s

sex
male      18
female    18
male      18
female    18
male      18
          ..
female    64
male      64
male      64
female    64
female    64
Name: age, Length: 1338, dtype: int64

In [80]:
#sort_index
s.sort_index(inplace=True)#inplace True =retyrn = None# inplace= Flace = Return=new dataFrme

s

sex
female    64
female    34
female    34
female    34
female    34
          ..
male      36
male      36
male      36
male      34
male      39
Name: age, Length: 1338, dtype: int64

In [81]:
s

sex
female    64
female    34
female    34
female    34
female    34
          ..
male      36
male      36
male      36
male      34
male      39
Name: age, Length: 1338, dtype: int64

Series Maths Mathods

In [82]:
[]#Count
#vk=pd.read_csv('IPL_Ball_by_Ball_2008_2022.csv',index_col='match_no')

vk = pd.read_csv('kohli_ipl.csv',index_col='match_no')
df=vk.squeeze()
df
vk.count()#count total numbr of item count kora de#and size mesing value o count kora

runs    215
dtype: int64

In [83]:
[]#sum->product
vk.sum()
df=vk.product()
df

runs    0
dtype: int64

In [84]:
movies=pd.read_csv('bollywood.csv')
movies.squeeze()

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [85]:
Subs=pd.read_csv('subs.csv')
Subs.squeeze()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [86]:
[]#mean->mediam->std->var
Subs.mean()
print(vk.median())
print(movies.mode())
print(Subs.std())
print(vk.var())

runs    24.0
dtype: float64
                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN
Subscribers gained    62.675023
dtype: float64
runs    688.002478
dtype: float64

In [87]:
[]#min/max
Subs.min()
Subs.max()

Subscribers gained    396
dtype: int64

In [88]:
[]#describe
vk.describe()
Subs.describe()

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

Series indexcing

In [89]:
#Integer Indexing
x=pd.Series([12,13,14,15,33,55,66])
x[1]

np.int64(13)

In [90]:
#Negative indexing
#default integer(Error)because pandas not undestand label ,/position,, confused #x.iloc[-1] this works 
#But Custom Label (works )

In [91]:
#Slicing
vk[5:9]

          runs
match_no
6            9
7           34
8            0
9           21

In [92]:
#negative Slicing
vk[-5:]

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [99]:
#fancy indexing
vk.iloc[[2,3,4,5]]

          runs
match_no
3           13
4           12
5            1
6            9

In [124]:
#index with label >fancy indexcing
movies
#movies.set_index('movie',inplace=True)
#ovies.loc['Hum Tumhare Hain Sanam']

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [127]:
movies.loc['Hum Tumhare Hain Sanam']

lead    Shah Rukh Khan
Name: Hum Tumhare Hain Sanam, dtype: str

In [125]:
movies.loc['Hum Tumhare Hain Sanam']

lead    Shah Rukh Khan
Name: Hum Tumhare Hain Sanam, dtype: str