#''Part A: Day 1 – DataFrame Basics & Attributes

In [2]:
import pandas as pd

In [3]:
df=pd.read_json("practice_dataset1.json")
df

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [4]:
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()
df5=df.copy()
df6=df.copy()
df7=df.copy()

In [5]:
#Find the number of rows and columns in the DataFrame.
print(df.shape)

(10, 12)

In [6]:
#Find the total number of elements in the DataFrame.
print(df.size)

120

In [7]:
#Check the number of dimensions of the DataFrame.
print(df.ndim)

2

In [8]:
#Get all the column names.
print(list(df.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [9]:
#See how the row index is arranged.
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [10]:
#Check the data type of each column.
print(df.dtypes)

id              int64
name              str
age             int64
sex               str
salary        float64
bmi           float64
children      float64
smoker            str
region            str
department        str
join_date         str
is_manager       bool
dtype: object

In [11]:
##View the summary of the DataFrame.
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     str
 2   age         10 non-null     int64
 3   sex         10 non-null     str
 4   salary      9 non-null      float64
 5   bmi         10 non-null     float64
 6   children    9 non-null      float64
 7   smoker      10 non-null     str
 8   region      10 non-null     str
 9   department  10 non-null     str
 10  join_date   10 non-null     str
 11  is_manager  10 non-null     bool
dtypes: bool(1), float64(3), int64(2), str(6)
memory usage: 1018.0 bytes
None

In [12]:
#View all values as a NumPy array.
print(df.values)

[[1 'John' 28 'M' 55000.0 24.5 2.0 'Yes' 'North' 'Sales' '2020-01-15'
  False]
 [2 'Jane' 34 'F' 62000.0 22.1 1.0 'No' 'South' 'Marketing' '2019-06-23'
  True]
 [3 'Bob' 45 'M' 70000.0 27.8 3.0 'Yes' 'East' 'IT' '2015-09-10' False]
 [4 'Alice' 29 'F' 58000.0 23.4 0.0 'No' 'West' 'HR' '2021-03-12' False]
 [5 'Mike' 38 'M' 65000.0 28.2 nan 'Yes' 'North' 'Finance' '2018-12-01'
  True]
 [6 'Linda' 31 'F' 60000.0 21.9 2.0 'No' 'South' 'IT' '2020-07-08' False]
 [7 'Steve' 42 'M' 72000.0 26.5 1.0 'Yes' 'East' 'Marketing' '2016-11-20'
  True]
 [8 'Karen' 36 'F' nan 24.9 2.0 'No' 'West' 'Sales' '2017-04-30' False]
 [9 'Tom' 39 'M' 68000.0 29.1 3.0 'Yes' 'North' 'Finance' '2015-05-14'
  False]
 [10 'Susan' 33 'F' 61000.0 23.0 1.0 'No' 'South' 'HR' '2019-08-25' False]]

In [13]:
#Transpose the DataFrame.
print(df.T)

                     0           1           2           3           4  \
id                   1           2           3           4           5
name              John        Jane         Bob       Alice        Mike
age                 28          34          45          29          38
sex                  M           F           M           F           M
salary         55000.0     62000.0     70000.0     58000.0     65000.0
bmi               24.5        22.1        27.8        23.4        28.2
children           2.0         1.0         3.0         0.0         NaN
smoker             Yes          No         Yes          No         Yes
region           North       South        East        West       North
department       Sales   Marketing          IT          HR     Finance
join_date   2020-01-15  2019-06-23  2015-09-10  2021-03-12  2018-12-01
is_manager       False        True       False       False        True

                     5           6           7           8           9
id                   6           7           8           9          10
name             Linda       Steve       Karen         Tom       Susan
age                 31          42          36          39          33
sex                  F           M           F           M           F
salary         60000.0     72000.0         NaN     68000.0     61000.0
bmi               21.9        26.5        24.9        29.1        23.0
children           2.0         1.0         2.0         3.0         1.0
smoker              No         Yes          No         Yes          No
region           South        East        West       North       South
department          IT   Marketing       Sales     Finance          HR
join_date   2020-07-08  2016-11-20  2017-04-30  2015-05-14  2019-08-25
is_manager       False        True       False       False       False

In [14]:
#View the first 5 rows.
print(df.head())

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True

View the last 5 rows.

In [15]:
print(df.tail())

   id   name  age sex   salary   bmi  children smoker region department  \
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

View summary statistics of numeric columns.

In [16]:
print(df2.describe())

             id        age        salary        bmi  children
count  10.00000  10.000000      9.000000  10.000000  9.000000
mean    5.50000  35.500000  63444.444444  25.140000  1.666667
std     3.02765   5.562773   5703.312877   2.620093  1.000000
min     1.00000  28.000000  55000.000000  21.900000  0.000000
25%     3.25000  31.500000  60000.000000  23.100000  1.000000
50%     5.50000  35.000000  62000.000000  24.700000  2.000000
75%     7.75000  38.750000  68000.000000  27.475000  2.000000
max    10.00000  45.000000  72000.000000  29.100000  3.000000

Count non-null values.

In [17]:
print(df.notnull())

     id  name   age   sex  salary   bmi  children  smoker  region  department  \
0  True  True  True  True    True  True      True    True    True        True
1  True  True  True  True    True  True      True    True    True        True
2  True  True  True  True    True  True      True    True    True        True
3  True  True  True  True    True  True      True    True    True        True
4  True  True  True  True    True  True     False    True    True        True
5  True  True  True  True    True  True      True    True    True        True
6  True  True  True  True    True  True      True    True    True        True
7  True  True  True  True   False  True      True    True    True        True
8  True  True  True  True    True  True      True    True    True        True
9  True  True  True  True    True  True      True    True    True        True

   join_date  is_manager
0       True        True
1       True        True
2       True        True
3       True        True
4       True        True
5       True        True
6       True        True
7       True        True
8       True        True
9       True        True

Find column-wise mean.

In [18]:
data=df1.mean(numeric_only=True)
data

id                5.500000
age              35.500000
salary        63444.444444
bmi              25.140000
children          1.666667
is_manager        0.300000
dtype: float64

Find column-wise median.

In [19]:
print(df1.median(numeric_only=True))

id                5.5
age              35.0
salary        62000.0
bmi              24.7
children          2.0
is_manager        0.0
dtype: float64

Find column-wise sum.

In [20]:
print(df.sum(numeric_only=True))

id                55.0
age              355.0
salary        571000.0
bmi              251.4
children          15.0
is_manager         3.0
dtype: float64


Find column-wise minimum.

In [21]:
print(df.min(numeric_only=True))

id                  1
age                28
salary        55000.0
bmi              21.9
children          0.0
is_manager      False
dtype: object

Find column-wise maximum.

In [22]:
print(df.max(numeric_only=True))

id                 10
age                45
salary        72000.0
bmi              29.1
children          3.0
is_manager       True
dtype: object

In [23]:
print(df.memory_usage())

Index         128
id             80
name           80
age            80
sex            80
salary         80
bmi            80
children       80
smoker         80
region         80
department     80
join_date      80
is_manager     10
dtype: int64

View the frequency count of the “region” column.

In [24]:
print(df2["region"].value_counts())

region
North    3
South    3
East     2
West     2
Name: count, dtype: int64

Get unique values of the “age” column.

In [25]:
print(df["age"].unique())

[28 34 45 29 38 31 42 36 39 33]

Part C: Day 2 – Modification Functions

33. Add a new column.

In [26]:
df1["new_columnn"]=[10,20,30,40,4,50,66,77,88,99]

34. Rename a column

In [27]:
df1.rename(columns={"age":"Age"})

,id,name,Age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,88
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99

In [28]:
df1.rename(columns={"salary":"Salary"})

,id,name,age,sex,Salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,88
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99

In [29]:
df2.rename(columns={"region":"Region"})

,id,name,age,sex,salary,bmi,children,smoker,Region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [30]:
df1["new_column"]=[10,29,33,44,55,66,88,89,99,66]
df1

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,29
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30,33
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,44
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4,55
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50,66
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66,88
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77,89
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,88,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99,66

35. Drop a column.

In [31]:
df1.drop("new_column",axis=1,inplace=False)

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,88
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99

36. Update a specific row-column value.

In [32]:
df2.at[0,"age"]=33
df2

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,33,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [33]:
df2.at[0,"Salary"]= "4000"
df2

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,1,John,33,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,4000
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

In [34]:
df2.at[0,"children"] =3.0
df2

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,1,John,33,M,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

37. Insert a new column at a specific position.

# Bhul: Row ache 10-ta, kintu list-e value 1-ta
df['children'] = [3.0] 

# Sothik: Shudhu value dilei hobe (Broadcasting)
df['children'] = 3.0

In [35]:
df2.insert(2,"new_bmi",[33,22,33,44,55,66,77,88,99,90])
df2

,id,name,new_bmi,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,1,John,33,33,M,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
1,2,Jane,22,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,3,Bob,33,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,4,Alice,44,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,5,Mike,55,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,6,Linda,66,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,7,Steve,77,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,8,Karen,88,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,9,Tom,99,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,10,Susan,90,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

38. Copy the DataFrame and replace values in the copy.

In [36]:
data=df1.copy()
data["children"]=data["children"].replace(3.0,"no_childen",inplace=True)
data

C:\Users\Nado Jahan\AppData\Local\Temp\ipykernel_12868\993575540.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["children"]=data["children"].replace(3.0,"no_childen",inplace=True)

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,29
2,3,Bob,45,M,70000.0,27.8,no_childen,Yes,East,IT,2015-09-10,False,30,33
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,44
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4,55
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50,66
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66,88
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77,89
8,9,Tom,39,M,68000.0,29.1,no_childen,Yes,North,Finance,2015-05-14,False,88,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99,66

In [37]:
data["children"]=data["children"].replace(3.0,"no_childen")
data

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,29
2,3,Bob,45,M,70000.0,27.8,no_childen,Yes,East,IT,2015-09-10,False,30,33
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,44
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4,55
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50,66
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66,88
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77,89
8,9,Tom,39,M,68000.0,29.1,no_childen,Yes,North,Finance,2015-05-14,False,88,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99,66

39. Change the data type of a column.

In [38]:
df2['age'] = df2['age'].astype(float)
df2

,id,name,new_bmi,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,1,John,33,33.0,M,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
1,2,Jane,22,34.0,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,3,Bob,33,45.0,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,4,Alice,44,29.0,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,5,Mike,55,38.0,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,6,Linda,66,31.0,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,7,Steve,77,42.0,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,8,Karen,88,36.0,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,9,Tom,99,39.0,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,10,Susan,90,33.0,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

In [39]:
df2["salary"]=df2["salary"].astype(object)
df2

,id,name,new_bmi,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,1,John,33,33.0,M,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
1,2,Jane,22,34.0,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,3,Bob,33,45.0,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,4,Alice,44,29.0,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,5,Mike,55,38.0,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,6,Linda,66,31.0,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,7,Steve,77,42.0,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,8,Karen,88,36.0,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,9,Tom,99,39.0,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,10,Susan,90,33.0,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

40. Set a column as the index and then reset it.

In [40]:
# Column-ke index banano
df2.set_index('name', inplace=True)

# Index-ke abar normal column-e ferot ana
df2.reset_index(inplace=True)

In [41]:
df2.set_index("sex",inplace=True)
df2

,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
sex,,,,,,,,,,,,,
M,John,1,33,33.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
F,Jane,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
M,Bob,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
F,Alice,4,44,29.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
F,Linda,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
F,Karen,8,88,36.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
F,Susan,10,90,33.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

In [42]:
arr=df2.reset_index(inplace=True)#index ka 0 take count korar jonno
arr

41. Update values in some random rows.

# .at update the one value in datafeame
# but loc update a multiple  value in dataframe

In [43]:
random_index=df3.sample(n=2).index
df3.loc[random_index,"salary"]= 99999
print(df3.loc[random_index])

   id   name  age sex   salary   bmi  children smoker region department  \
1   2   Jane   34   F  99999.0  22.1       1.0     No  South  Marketing
5   6  Linda   31   F  99999.0  21.9       2.0     No  South         IT

    join_date  is_manager
1  2019-06-23        True
5  2020-07-08       False

In [44]:
random_indices = df2.sample(n=2).index
df2.loc[random_indices, 'name'] = 'Randomly Updated'
random_index
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,John,1,33,33.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
1,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
2,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
3,F,Alice,4,44,29.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
4,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
5,F,Linda,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN
6,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
7,F,Karen,8,88,36.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,Susan,10,90,33.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN

In [45]:
random2=df2.sample(n=4).index
df2.loc[random2,"age"]=55
print(df2.loc[random2])

  sex   name  id  new_bmi   age   salary   bmi  children smoker region  \
3   F  Alice   4       44  55.0  58000.0  23.4       0.0     No   West
7   F  Karen   8       88  55.0      NaN  24.9       2.0     No   West
9   F  Susan  10       90  55.0  61000.0  23.0       1.0     No  South
0   M   John   1       33  55.0  55000.0  24.5       3.0    Yes  North

  department   join_date  is_manager Salary
3         HR  2021-03-12       False    NaN
7      Sales  2017-04-30       False    NaN
9         HR  2019-08-25       False    NaN
0      Sales  2020-01-15       False   4000

In [46]:
## randomly row niba 
print(df2.sample(n=5))

  sex   name  id  new_bmi   age   salary   bmi  children smoker region  \
7   F  Karen   8       88  55.0      NaN  24.9       2.0     No   West
6   M  Steve   7       77  42.0  72000.0  26.5       1.0    Yes   East
5   F  Linda   6       66  31.0  60000.0  21.9       2.0     No  South
8   M    Tom   9       99  39.0  68000.0  29.1       3.0    Yes  North
4   M   Mike   5       55  38.0  65000.0  28.2       NaN    Yes  North

  department   join_date  is_manager Salary
7      Sales  2017-04-30       False    NaN
6  Marketing  2016-11-20        True    NaN
5         IT  2020-07-08       False    NaN
8    Finance  2015-05-14       False    NaN
4    Finance  2018-12-01        True    NaN

In [47]:
## datasset a percentange (%) Anujai data niba  jamon 20% akon
print(df2.sample(frac=0.2))

  sex   name  id  new_bmi   age   salary   bmi  children smoker region  \
5   F  Linda   6       66  31.0  60000.0  21.9       2.0     No  South
4   M   Mike   5       55  38.0  65000.0  28.2       NaN    Yes  North

  department   join_date  is_manager Salary
5         IT  2020-07-08       False    NaN
4    Finance  2018-12-01        True    NaN

In [48]:
print(df2.sample(frac=0.3))

  sex              name  id  new_bmi   age   salary   bmi  children smoker  \
6   M             Steve   7       77  42.0  72000.0  26.5       1.0    Yes
8   M               Tom   9       99  39.0  68000.0  29.1       3.0    Yes
1   F  Randomly Updated   2       22  34.0  62000.0  22.1       1.0     No

  region department   join_date  is_manager Salary
6   East  Marketing  2016-11-20        True    NaN
8  North    Finance  2015-05-14       False    NaN
1  South  Marketing  2019-06-23        True    NaN

In [49]:
# M learning a -er take data ke Shuffle kora
df2=df2.sample(frac=1).reset_index(drop=True)
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN
7,F,Karen,8,88,55.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,Linda,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN

In [71]:
df2.sample(frac=1).reset_index(drop=True)
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN
7,F,Karen,8,88,55.0,NaN,24.9,nochildern,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,saima,6,66,31.0,60000.0,21.9,nochildern,No,South,IT,2020-07-08,False,NaN

Part D: Day 2 – Cleaning Functions

42. Check for missing values.

42. Check for missing values.

In [51]:
df1.isna().sum()

id             0
name           0
age            0
sex            0
salary         1
bmi            0
children       1
smoker         0
region         0
department     0
join_date      0
is_manager     0
new_columnn    0
new_column     0
dtype: int64

43. Fill missing values.

In [52]:
df2.fillna(3)

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,3.0,Yes,North,Finance,2018-12-01,True,3
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,3
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,3
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,3
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,3
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,3
7,F,Karen,8,88,55.0,3,24.9,2.0,No,West,Sales,2017-04-30,False,3
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,3
9,F,Linda,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,3

45. Check for duplicate rows.

In [53]:
df2.duplicated("new_bmi")

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [54]:
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN
7,F,Karen,8,88,55.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,Linda,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN

46. Drop duplicate rows.

In [55]:
df1.drop_duplicates("name")

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_columnn,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,29
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30,33
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,44
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,4,55
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,50,66
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,66,88
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,77,89
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,88,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,99,66

47. Replace column values.

In [56]:
df2["name"]=df2["name"].replace("Linda","saima")
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN
7,F,Karen,8,88,55.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,saima,6,66,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,NaN

47. Replace column values.

In [57]:
df2["children"]=df2["children"].replace(2.0,"nochildern")
df2

,sex,name,id,new_bmi,age,salary,bmi,children,smoker,region,department,join_date,is_manager,Salary
0,M,Mike,5,55,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,NaN
1,F,Alice,4,44,55.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,NaN
2,F,Randomly Updated,2,22,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,NaN
3,M,John,1,33,55.0,55000.0,24.5,3.0,Yes,North,Sales,2020-01-15,False,4000
4,M,Randomly Updated,3,33,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,NaN
5,M,Steve,7,77,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,NaN
6,F,Susan,10,90,55.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,NaN
7,F,Karen,8,88,55.0,NaN,24.9,nochildern,No,West,Sales,2017-04-30,False,NaN
8,M,Tom,9,99,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,NaN
9,F,saima,6,66,31.0,60000.0,21.9,nochildern,No,South,IT,2020-07-08,False,NaN


#আপনি যদি একটি Lower Limit এবং একটি Upper Limit ঠিক করে দেন:

#যদি কোনো ভ্যালু লোয়ার লিমিটের চেয়ে কম হয়, সেটি বদলে লোয়ার লিমিট হয়ে যাবে।

#যদি কোনো ভ্যালু আপার লিমিটের চেয়ে বেশি হয়, সেটি বদলে আপার লিমিট হয়ে যাবে।

**বাকি ভ্যালুগুলো অপরিবর্তিত থাকবে
ধরা যাক আপনার কাছে একটি ডাটাফ্রেম আছে যেখানে কিছু স্টুডেন্টের মার্কস দেওয়া আছে, কিন্তু সেখানে ভুলবশত ০-এর নিচে এবং ১০০-এর উপরে কিছু মান চলে এসেছে।

In [58]:
#48. Clip column values within a range

#This is useful for handling outliers by capping values at a min/max threshold.

#Python
df2['new_bmi'].clip(lower=10, upper=100, inplace=True)

C:\Users\Nado Jahan\AppData\Local\Temp\ipykernel_12868\4110082429.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['new_bmi'].clip(lower=10, upper=100, inplace=True)

0    55
1    44
2    22
3    33
4    33
5    77
6    90
7    88
8    99
9    66
Name: new_bmi, dtype: int64

49. Check column-wise data types.

In [59]:
df2.dtypes

sex               str
name              str
id              int64
new_bmi         int64
age           float64
salary         object
bmi           float64
children       object
smoker            str
region            str
department        str
join_date         str
is_manager       bool
Salary            str
dtype: object

Part E: Mixed Day 1 + Day 2 Analysis

50. Check the DataFrame shape.

In [60]:
df2.shape

(10, 14)

51. Check the total number of elements.

In [61]:
df2.size

140

52. View summary statistics of numeric columns.

In [62]:
df2.describe()

             id    new_bmi        age        bmi
count  10.00000  10.000000  10.000000  10.000000
mean    5.50000  60.700000  44.900000  25.140000
std     3.02765  27.300997   9.492102   2.620093
min     1.00000  22.000000  31.000000  21.900000
25%     3.25000  35.750000  38.250000  23.100000
50%     5.50000  60.500000  43.500000  24.700000
75%     7.75000  85.250000  55.000000  27.475000
max    10.00000  99.000000  55.000000  29.100000

53. Find unique values column-wise.

In [63]:
df2["name"].unique

<bound method Series.unique of 0                Mike
1               Alice
2    Randomly Updated
3                John
4    Randomly Updated
5               Steve
6               Susan
7               Karen
8                 Tom
9               saima
Name: name, dtype: str>

54. Find max, min, mean, and median of columns.

In [64]:
df2.mean(numeric_only=True)
df2.max(numeric_only=True)
df2.median(numeric_only=True)

id             5.5
new_bmi       60.5
age           43.5
bmi           24.7
is_manager     0.0
dtype: float64

55. View correlation of numeric columns.

Pandas-এ corr() ফাংশনটি মূলত Correlation (সহসম্পর্ক) বের করার জন্য ব্যবহার করা হয়। সহজ কথায়, একটি ডাটাফ্রেমের একটি কলামের মান বাড়লে বা কমলে অন্য একটি কলামের মান কীভাবে পরিবর্তিত হয়, সেটি বোঝার জন্যই এটি ব্যবহার করা হয়।

এটি সাধারণত Numerical (সংখ্যাবাচক) কলামগুলোর মধ্যে সম্পর্ক দেখায়।

In [65]:
df2.corr(numeric_only=True)

                  id   new_bmi       age       bmi  is_manager
id          1.000000  0.965829  0.075392  0.168080   -0.189934
new_bmi     0.965829  1.000000  0.100631  0.249650   -0.236754
age         0.075392  0.100631  1.000000 -0.080686   -0.501623
bmi         0.168080  0.249650 -0.080686  1.000000    0.121152
is_manager -0.189934 -0.236754 -0.501623  0.121152    1.000000

56. Check the row index.

In [66]:
df2.index

RangeIndex(start=0, stop=10, step=1)



57. Check column-wise data types.

In [67]:
df2.dtypes

sex               str
name              str
id              int64
new_bmi         int64
age           float64
salary         object
bmi           float64
children       object
smoker            str
region            str
department        str
join_date         str
is_manager       bool
Salary            str
dtype: object

58. Try correlation without numeric columns and note observations.'''