In [41]:
import pandas as pd

In [42]:
df=pd.read_json("practice_dataset1.json")

In [43]:
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()

In [44]:
df["new_column"]=[10,20,30,40,50,60,70,80,99,44]
df

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [45]:
df.rename(columns={"age":"Age"})

,id,name,Age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [46]:
df.rename(columns={"salary":"Salary"})

,id,name,age,sex,Salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [47]:
df.drop("age",axis=1)

,id,name,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [48]:
#27.Position-based fast single value selection ব্যবহার করো।
df.iat[2,4]

np.float64(70000.0)

In [49]:
df.at[2,"salary"]=4444
df

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,4444.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [53]:
df33=df2.query('bmi >30 and smoker =="yes"')
df33

Empty DataFrame
Columns: [id, name, age, sex, salary, bmi, children, smoker, region, department, join_date, is_manager]
Index: []

In [ ]:
df[df["age"]>30]

,id,name,new_colum,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
1,2,Jane,22,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,33,45,M,4444.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
4,5,Mike,55,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,66,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,77,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,88,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,99,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,77,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

In [ ]:
df.insert(2,"new_colum",[11,22,33,44,55,66,77,88,99,77])

In [ ]:
df1.replace(2.0,"no_childer")

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,no_childer,Yes,North,Sales,2020-01-15,False
1,no_childer,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,no_childer,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,no_childer,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
df1["age"]=df1["age"].astype("float")
df1

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28.0,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34.0,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45.0,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29.0,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38.0,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31.0,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42.0,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36.0,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39.0,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33.0,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
df1.set_index("name")

,id,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
name,,,,,,,,,,,
John,1,28.0,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
Jane,2,34.0,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
Bob,3,45.0,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
Alice,4,29.0,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
Mike,5,38.0,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
Linda,6,31.0,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
Steve,7,42.0,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
Karen,8,36.0,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
Tom,9,39.0,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
Susan,10,33.0,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
df1.set_index("sex")

,id,name,age,salary,bmi,children,smoker,region,department,join_date,is_manager
sex,,,,,,,,,,,
M,1,John,28.0,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
F,2,Jane,34.0,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
M,3,Bob,45.0,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
F,4,Alice,29.0,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
M,5,Mike,38.0,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
F,6,Linda,31.0,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
M,7,Steve,42.0,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
F,8,Karen,36.0,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
M,9,Tom,39.0,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
F,10,Susan,33.0,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
random_indics=df1.sample(n=5).index
df1.loc[random_indics,"salary"]= 9999
df1.loc[random_indics]

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
3,4,Alice,29.0,F,9999.0,23.4,0.0,No,West,HR,2021-03-12,False
1,2,Jane,34.0,F,9999.0,22.1,1.0,No,South,Marketing,2019-06-23,True
0,1,John,28.0,M,9999.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
5,6,Linda,31.0,F,9999.0,21.9,2.0,No,South,IT,2020-07-08,False
4,5,Mike,38.0,M,9999.0,28.2,NaN,Yes,North,Finance,2018-12-01,True

In [ ]:
df2

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
# creat nmpy array 
df2.to_numpy

<bound method DataFrame.to_numpy of    id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False  >

In [ ]:
df2.values

array([[1, 'John', 28, 'M', 55000.0, 24.5, 2.0, 'Yes', 'North', 'Sales',
        '2020-01-15', False],
       [2, 'Jane', 34, 'F', 62000.0, 22.1, 1.0, 'No', 'South',
        'Marketing', '2019-06-23', True],
       [3, 'Bob', 45, 'M', 70000.0, 27.8, 3.0, 'Yes', 'East', 'IT',
        '2015-09-10', False],
       [4, 'Alice', 29, 'F', 58000.0, 23.4, 0.0, 'No', 'West', 'HR',
        '2021-03-12', False],
       [5, 'Mike', 38, 'M', 65000.0, 28.2, nan, 'Yes', 'North',
        'Finance', '2018-12-01', True],
       [6, 'Linda', 31, 'F', 60000.0, 21.9, 2.0, 'No', 'South', 'IT',
        '2020-07-08', False],
       [7, 'Steve', 42, 'M', 72000.0, 26.5, 1.0, 'Yes', 'East',
        'Marketing', '2016-11-20', True],
       [8, 'Karen', 36, 'F', nan, 24.9, 2.0, 'No', 'West', 'Sales',
        '2017-04-30', False],
       [9, 'Tom', 39, 'M', 68000.0, 29.1, 3.0, 'Yes', 'North', 'Finance',
        '2015-05-14', False],
       [10, 'Susan', 33, 'F', 61000.0, 23.0, 1.0, 'No', 'South', 'HR',
        '2019-08-25', False]], dtype=object)

In [ ]:
df2["salary"].mean()
df2["salary"].max()

np.float64(72000.0)

In [ ]:
df2[["age","bmi"]]

   age   bmi
0   28  24.5
1   34  22.1
2   45  27.8
3   29  23.4
4   38  28.2
5   31  21.9
6   42  26.5
7   36  24.9
8   39  29.1
9   33  23.0

In [ ]:
#24.Label ব্যবহার করে নির্দিষ্ট row এবং column এর মান বের করো।
df2.loc[1:5,["name","age"]]

    name  age
1   Jane   34
2    Bob   45
3  Alice   29
4   Mike   38
5  Linda   31

In [ ]:
#Position ব্যবহার করে নির্দিষ্ট row এবং column এর মান বের করো।

In [ ]:
df2=df2.iloc[1:4,5:7]
df2

    bmi  children
1  22.1       1.0
2  27.8       3.0
3  23.4       0.0

In [ ]:
#27.Position-based fast single value selection ব্যবহার করো।
new_row_colum = df3.iat[2,4]
new_row_colum

np.float64(70000.0)

In [ ]:
# The serics  value(output farmat)
new_position=df3.iat[3,4]
new_position

np.float64(58000.0)

In [ ]:
#28.প্রথম 10 row এবং প্রথম 3 column বের করো।
new_row_colum1 = df3.head(10).iloc[: , :3]
new_row_colum1

   id   name  age
0   1   John   28
1   2   Jane   34
2   3    Bob   45
3   4  Alice   29
4   5   Mike   38
5   6  Linda   31
6   7  Steve   42
7   8  Karen   36
8   9    Tom   39
9  10  Susan   33

In [ ]:
#Output Format: Usually a DataFrame.
new_position1=df3.head(10).iloc[:,:3]
new_position1

   id   name  age
0   1   John   28
1   2   Jane   34
2   3    Bob   45
3   4  Alice   29
4   5   Mike   38
5   6  Linda   31
6   7  Steve   42
7   8  Karen   36
8   9    Tom   39
9  10  Susan   33

In [ ]:
#condition onujayi data filter kora ba khunje ber kora.
df3.query('bmi > 25 and smoker == "Yes"')

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False

In [54]:
new_data=pd.concat([df.head(10),df.tail(4)]).reset_index(drop=True)
new_data

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20
2,3,Bob,45,M,4444.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44
10,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70
11,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80
12,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99
13,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44

 Add new column 
 পদ্ধতি,কখন ব্যবহার করবেন?
df['col'],সাধারণ এবং দ্রুত নতুন কলাম যোগ করতে।
assign(),মেথড চেইনিং করতে বা মূল ডেটাফ্রেম ঠিক রাখতে।
insert(),কলামের পজিশন (Location) নির্দিষ্ট করতে চাইলে।
loc,কন্ডিশন বা শর্তের ওপর ভিত্তি করে মান বসাতে।
apply(),জটিল কোনো ফাংশন বা লজিক প্রতিটি রো-তে চালাতে।

In [57]:
df3['new_col'] = [10, 20, 30,55,66,77,88,99,00,88]

In [76]:
#2 ০ নম্বর ইনডেক্সে অর্থাৎ একদম শুরুতে 'ID' কলাম যোগ করা
df2.insert(0, 'spoking', [101, 102, 103,22,33,44,55,33,44,88])

In [ ]:
#3 যাদের বয়স ১৮-এর বেশি, তাদের জন্য 'Status' কলামে 'Adult' বসানো
df.loc[df['age'] >= 18, 'Status'] = 'Adult'

In [ ]:
#4
df.eval('Total = Physics + Chemistry', inplace=True)

In [82]:
# লিঙ্গ অনুযায়ী টাইটেল ঠিক করা
df['Title'] = df['sex'].map({'Male': 'Mr.', 'Female': 'Ms.'})
df

# ফাংশন ব্যবহার করে
df['Double_A'] = df['salary'].apply(lambda x: x * 2)
df

,ID,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column,Double,Title,Double_A
0,101,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,14.0,NaN,110000.0
1,102,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,17.0,NaN,124000.0
2,103,3,Bob,45,M,4444.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30,22.5,NaN,8888.0
3,22,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,14.5,NaN,116000.0
4,33,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50,19.0,NaN,130000.0
5,44,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60,15.5,NaN,120000.0
6,55,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70,21.0,NaN,144000.0
7,66,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80,18.0,NaN,NaN
8,77,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99,19.5,NaN,136000.0
9,88,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44,16.5,NaN,122000.0

In [77]:
df["Double"]=df["age"].apply(lambda x: x/2)

In [ ]:
# 'C' নামে নতুন কলাম যোগ করা
df_new = df.assign(C = [5, 6])

Pandas-এ assign() মেথডটি মূলত ডেটাফ্রেমে নতুন কলাম যোগ করার জন্য অথবা পুরানো কলামের মান পরিবর্তন করার জন্য ব্যবহার করা হয়।

In [ ]:
# A কলামের মানের সাথে ১০ যোগ করে নতুন কলাম 'D' তৈরি
df_new = df.assign(D = lambda x: x['A'] + 10)

In [86]:
df_=df.assign(salary=lambda x: x['age']+10)
df_

,ID,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column,Double,Title,Double_A
0,101,1,John,28,M,38,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,14.0,NaN,110000.0
1,102,2,Jane,34,F,44,22.1,1.0,No,South,Marketing,2019-06-23,True,20,17.0,NaN,124000.0
2,103,3,Bob,45,M,55,27.8,3.0,Yes,East,IT,2015-09-10,False,30,22.5,NaN,8888.0
3,22,4,Alice,29,F,39,23.4,0.0,No,West,HR,2021-03-12,False,40,14.5,NaN,116000.0
4,33,5,Mike,38,M,48,28.2,NaN,Yes,North,Finance,2018-12-01,True,50,19.0,NaN,130000.0
5,44,6,Linda,31,F,41,21.9,2.0,No,South,IT,2020-07-08,False,60,15.5,NaN,120000.0
6,55,7,Steve,42,M,52,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70,21.0,NaN,144000.0
7,66,8,Karen,36,F,46,24.9,2.0,No,West,Sales,2017-04-30,False,80,18.0,NaN,NaN
8,77,9,Tom,39,M,49,29.1,3.0,Yes,North,Finance,2015-05-14,False,99,19.5,NaN,136000.0
9,88,10,Susan,33,F,43,23.0,1.0,No,South,HR,2019-08-25,False,44,16.5,NaN,122000.0

In [89]:
df.rename({'id':'ID'},axis=1,inplace=True)
df

,ID,ID,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager,new_column,Double,Title,Double_A
0,101,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False,10,14.0,NaN,110000.0
1,102,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True,20,17.0,NaN,124000.0
2,103,3,Bob,45,M,4444.0,27.8,3.0,Yes,East,IT,2015-09-10,False,30,22.5,NaN,8888.0
3,22,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False,40,14.5,NaN,116000.0
4,33,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True,50,19.0,NaN,130000.0
5,44,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False,60,15.5,NaN,120000.0
6,55,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True,70,21.0,NaN,144000.0
7,66,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False,80,18.0,NaN,NaN
8,77,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False,99,19.5,NaN,136000.0
9,88,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False,44,16.5,NaN,122000.0