In [2]:
import pandas as pd

In [3]:
data_set=pd.read_json("practice_dataset1.json")
data_set

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [4]:
data1=data_set.copy()
d2= data_set.copy()
d3= data_set.copy()
d4= data_set.copy()
d5=data_set.copy()

In [5]:
print(data1)

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [6]:
d2

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [7]:
d2["salary"]=d2["salary"].fillna(d2["salary"].mean())
print(d2)

   id   name  age sex        salary   bmi  children smoker region department  \
0   1   John   28   M  55000.000000  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.000000  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.000000  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.000000  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.000000  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.000000  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.000000  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.000000  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [8]:
print(d2.shape)

(10, 12)

In [9]:
print(d2.size)

120

In [10]:
print(list(d2.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [11]:
print(d2.rename(columns=({'age':'Age'})))

   id   name  Age sex        salary   bmi  children smoker region department  \
0   1   John   28   M  55000.000000  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.000000  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.000000  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.000000  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.000000  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.000000  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.000000  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.000000  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [12]:
print(d2.rename(columns=({'salary':'Salary'})))

   id   name  age sex        Salary   bmi  children smoker region department  \
0   1   John   28   M  55000.000000  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.000000  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.000000  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.000000  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.000000  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.000000  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.000000  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.000000  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [13]:
print(d2.select_dtypes(include='float64'))

         salary   bmi  children
0  55000.000000  24.5       2.0
1  62000.000000  22.1       1.0
2  70000.000000  27.8       3.0
3  58000.000000  23.4       0.0
4  65000.000000  28.2       NaN
5  60000.000000  21.9       2.0
6  72000.000000  26.5       1.0
7  63444.444444  24.9       2.0
8  68000.000000  29.1       3.0
9  61000.000000  23.0       1.0

In [14]:
d2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     str
 2   age         10 non-null     int64
 3   sex         10 non-null     str
 4   salary      10 non-null     float64
 5   bmi         10 non-null     float64
 6   children    9 non-null      float64
 7   smoker      10 non-null     str
 8   region      10 non-null     str
 9   department  10 non-null     str
 10  join_date   10 non-null     str
 11  is_manager  10 non-null     bool
dtypes: bool(1), float64(3), int64(2), str(6)
memory usage: 1018.0 bytes

In [15]:
print(d2.select_dtypes(include='object'))

    name sex smoker region department   join_date
0   John   M    Yes  North      Sales  2020-01-15
1   Jane   F     No  South  Marketing  2019-06-23
2    Bob   M    Yes   East         IT  2015-09-10
3  Alice   F     No   West         HR  2021-03-12
4   Mike   M    Yes  North    Finance  2018-12-01
5  Linda   F     No  South         IT  2020-07-08
6  Steve   M    Yes   East  Marketing  2016-11-20
7  Karen   F     No   West      Sales  2017-04-30
8    Tom   M    Yes  North    Finance  2015-05-14
9  Susan   F     No  South         HR  2019-08-25

C:\Users\Nado Jahan\AppData\Local\Temp\ipykernel_15228\1962856944.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(d2.select_dtypes(include='object'))

In [16]:
print(d2.ndim)

2

In [17]:
print(d2.size)

120

In [18]:
print(d2.columns)

Index(['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker',
       'region', 'department', 'join_date', 'is_manager'],
      dtype='str')

In [19]:
print(list(d2.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [20]:
#See how the row index is arranged.

print(d2.index)

RangeIndex(start=0, stop=10, step=1)

In [21]:
#iVew all values as a NumPy array.
print(d2.values)

[[1 'John' 28 'M' 55000.0 24.5 2.0 'Yes' 'North' 'Sales' '2020-01-15'
  False]
 [2 'Jane' 34 'F' 62000.0 22.1 1.0 'No' 'South' 'Marketing' '2019-06-23'
  True]
 [3 'Bob' 45 'M' 70000.0 27.8 3.0 'Yes' 'East' 'IT' '2015-09-10' False]
 [4 'Alice' 29 'F' 58000.0 23.4 0.0 'No' 'West' 'HR' '2021-03-12' False]
 [5 'Mike' 38 'M' 65000.0 28.2 nan 'Yes' 'North' 'Finance' '2018-12-01'
  True]
 [6 'Linda' 31 'F' 60000.0 21.9 2.0 'No' 'South' 'IT' '2020-07-08' False]
 [7 'Steve' 42 'M' 72000.0 26.5 1.0 'Yes' 'East' 'Marketing' '2016-11-20'
  True]
 [8 'Karen' 36 'F' 63444.444444444445 24.9 2.0 'No' 'West' 'Sales'
  '2017-04-30' False]
 [9 'Tom' 39 'M' 68000.0 29.1 3.0 'Yes' 'North' 'Finance' '2015-05-14'
  False]
 [10 'Susan' 33 'F' 61000.0 23.0 1.0 'No' 'South' 'HR' '2019-08-25' False]]

In [22]:
#Transpose the DataFrame.
print(d2.T)

                     0           1           2           3           4  \
id                   1           2           3           4           5
name              John        Jane         Bob       Alice        Mike
age                 28          34          45          29          38
sex                  M           F           M           F           M
salary         55000.0     62000.0     70000.0     58000.0     65000.0
bmi               24.5        22.1        27.8        23.4        28.2
children           2.0         1.0         3.0         0.0         NaN
smoker             Yes          No         Yes          No         Yes
region           North       South        East        West       North
department       Sales   Marketing          IT          HR     Finance
join_date   2020-01-15  2019-06-23  2015-09-10  2021-03-12  2018-12-01
is_manager       False        True       False       False        True

                     5           6             7           8           9
id                   6           7             8           9          10
name             Linda       Steve         Karen         Tom       Susan
age                 31          42            36          39          33
sex                  F           M             F           M           F
salary         60000.0     72000.0  63444.444444     68000.0     61000.0
bmi               21.9        26.5          24.9        29.1        23.0
children           2.0         1.0           2.0         3.0         1.0
smoker              No         Yes            No         Yes          No
region           South        East          West       North       South
department          IT   Marketing         Sales     Finance          HR
join_date   2020-07-08  2016-11-20    2017-04-30  2015-05-14  2019-08-25
is_manager       False        True         False       False       False

In [23]:
print(d2.head(5))

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True

In [24]:
print(d2.tail(5))

   id   name  age sex        salary   bmi  children smoker region department  \
5   6  Linda   31   F  60000.000000  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.000000  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.000000  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000  23.0       1.0     No  South         HR

    join_date  is_manager
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [25]:
#View summary statistics of numeric columns.

print(d2.describe())

             id        age        salary        bmi  children
count  10.00000  10.000000     10.000000  10.000000  9.000000
mean    5.50000  35.500000  63444.444444  25.140000  1.666667
std     3.02765   5.562773   5377.134948   2.620093  1.000000
min     1.00000  28.000000  55000.000000  21.900000  0.000000
25%     3.25000  31.500000  60250.000000  23.100000  1.000000
50%     5.50000  35.000000  62722.222222  24.700000  2.000000
75%     7.75000  38.750000  67250.000000  27.475000  2.000000
max    10.00000  45.000000  72000.000000  29.100000  3.000000

In [26]:
print(d2.isnull())

      id   name    age    sex  salary    bmi  children  smoker  region  \
0  False  False  False  False   False  False     False   False   False
1  False  False  False  False   False  False     False   False   False
2  False  False  False  False   False  False     False   False   False
3  False  False  False  False   False  False     False   False   False
4  False  False  False  False   False  False      True   False   False
5  False  False  False  False   False  False     False   False   False
6  False  False  False  False   False  False     False   False   False
7  False  False  False  False   False  False     False   False   False
8  False  False  False  False   False  False     False   False   False
9  False  False  False  False   False  False     False   False   False

   department  join_date  is_manager
0       False      False       False
1       False      False       False
2       False      False       False
3       False      False       False
4       False      False       False
5       False      False       False
6       False      False       False
7       False      False       False
8       False      False       False
9       False      False       False

In [27]:
# প্রতিটি কলামের আলাদা আলাদা গড় বের করার জন্য
print(d2.mean(numeric_only=True))

id                5.500000
age              35.500000
salary        63444.444444
bmi              25.140000
children          1.666667
is_manager        0.300000
dtype: float64

In [28]:
print(d2.median(numeric_only=True))

id                5.500000
age              35.000000
salary        62722.222222
bmi              24.700000
children          2.000000
is_manager        0.000000
dtype: float64

In [29]:
print(d2.max(numeric_only=True))

id                 10
age                45
salary        72000.0
bmi              29.1
children          3.0
is_manager       True
dtype: object

In [30]:
print(d2.min(numeric_only=True))

id                  1
age                28
salary        55000.0
bmi              21.9
children          0.0
is_manager      False
dtype: object

In [31]:
#Get unique values of the “age” column.
print(d2['age'].unique)

<bound method Series.unique of 0    28
1    34
2    45
3    29
4    38
5    31
6    42
7    36
8    39
9    33
Name: age, dtype: int64>

In [32]:
print(d2['salary'].unique)

<bound method Series.unique of 0    55000.000000
1    62000.000000
2    70000.000000
3    58000.000000
4    65000.000000
5    60000.000000
6    72000.000000
7    63444.444444
8    68000.000000
9    61000.000000
Name: salary, dtype: float64>

In [33]:
#Find the number of unique values in each column.
print(d2.columns.unique)# not work

<bound method Index.unique of Index(['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker',
       'region', 'department', 'join_date', 'is_manager'],
      dtype='str')>

In [51]:
# প্রতিটি কলামের ভেতরের ইউনিক মানের সংখ্যা দেখার জন্য
##Find the number of unique values in each column.

print(d2.nunique())

id            10
name          10
age           10
sex            2
salary        10
bmi           10
children       4
smoker         2
region         4
department     5
join_date     10
is_manager     2
dtype: int64

In [49]:

print(d4.nunique())

id            10
name          10
age           10
sex            2
salary         9
bmi           10
children       4
smoker         2
region         4
department     5
join_date     10
is_manager     2
dtype: int64

In [36]:
print(d3.nunique())

id            10
name          10
age           10
sex            2
salary         9
bmi           10
children       4
smoker         2
region         4
department     5
join_date     10
is_manager     2
dtype: int64

In [37]:
# 'region' কলামের প্রতিটি মান কতবার আছে তা দেখার জন্য
print(d2['region'].value_counts())

region
North    3
South    3
East     2
West     2
Name: count, dtype: int64

In [46]:
print(d2['salary'].value_counts())

salary
55000.000000    1
62000.000000    1
70000.000000    1
58000.000000    1
65000.000000    1
60000.000000    1
72000.000000    1
63444.444444    1
68000.000000    1
61000.000000    1
Name: count, dtype: int64

In [47]:
print(d2['age'].value_counts())

age
28    1
34    1
45    1
29    1
38    1
31    1
42    1
36    1
39    1
33    1
Name: count, dtype: int64

In [39]:
print(d2.nunique())

id            10
name          10
age           10
sex            2
salary        10
bmi           10
children       4
smoker         2
region         4
department     5
join_date     10
is_manager     2
dtype: int64

In [40]:
print(d2['age'].value_counts())

age
28    1
34    1
45    1
29    1
38    1
31    1
42    1
36    1
39    1
33    1
Name: count, dtype: int64

In [41]:
print(d2['salary'].value_counts())

salary
55000.000000    1
62000.000000    1
70000.000000    1
58000.000000    1
65000.000000    1
60000.000000    1
72000.000000    1
63444.444444    1
68000.000000    1
61000.000000    1
Name: count, dtype: int64

In [42]:
print(d2['age'])####

0    28
1    34
2    45
3    29
4    38
5    31
6    42
7    36
8    39
9    33
Name: age, dtype: int64

In [43]:
# Select both “age” and “bmi” columns together.
print(d2[['age','salary']])

   age        salary
0   28  55000.000000
1   34  62000.000000
2   45  70000.000000
3   29  58000.000000
4   38  65000.000000
5   31  60000.000000
6   42  72000.000000
7   36  63444.444444
8   39  68000.000000
9   33  61000.000000

In [44]:
# 'age' এবং 'bmi' কলাম দুটি একসাথে সিলেক্ট করার জন্য
print(d2[['age', 'bmi']])

   age   bmi
0   28  24.5
1   34  22.1
2   45  27.8
3   29  23.4
4   38  28.2
5   31  21.9
6   42  26.5
7   36  24.9
8   39  29.1
9   33  23.0

In [45]:
print(d2[['age','bmi']])

   age   bmi
0   28  24.5
1   34  22.1
2   45  27.8
3   29  23.4
4   38  28.2
5   31  21.9
6   42  26.5
7   36  24.9
8   39  29.1
9   33  23.0