In [2]:
import pandas as pd

In [3]:
data_set=pd.read_json("practice_dataset1.json")
data_set

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [4]:
data_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     str
 2   age         10 non-null     int64
 3   sex         10 non-null     str
 4   salary      9 non-null      float64
 5   bmi         10 non-null     float64
 6   children    9 non-null      float64
 7   smoker      10 non-null     str
 8   region      10 non-null     str
 9   department  10 non-null     str
 10  join_date   10 non-null     str
 11  is_manager  10 non-null     bool
dtypes: bool(1), float64(3), int64(2), str(6)
memory usage: 1018.0 bytes

In [5]:
data_set.head()

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True

In [6]:
data_set.tail()

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [7]:
d1= data_set.copy()
d2= data_set.copy()
d3= data_set.copy()
d4= data_set.copy()
d5= data_set.copy()
d6= data_set.copy()

In [8]:
print(d1)

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [9]:
data_set.columns=["ID","name","Age","SEx","Salary","Bmi","Childen","Smoker","REgion","Department","Jion_Data","Is_Manageer"]
data_set

,ID,name,Age,SEx,Salary,Bmi,Childen,Smoker,REgion,Department,Jion_Data,Is_Manageer
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [10]:
data_set.drop(["Bmi"],axis=1,inplace=True)
data_set

,ID,name,Age,SEx,Salary,Childen,Smoker,REgion,Department,Jion_Data,Is_Manageer
0,1,John,28,M,55000.0,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,1.0,No,South,HR,2019-08-25,False

In [11]:
data_set.dropna()
data_set.fillna(3)

,ID,name,Age,SEx,Salary,Childen,Smoker,REgion,Department,Jion_Data,Is_Manageer
0,1,John,28,M,55000.0,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,3.0,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,3.0,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,1.0,No,South,HR,2019-08-25,False

In [12]:
data_set.fillna(5.5)

,ID,name,Age,SEx,Salary,Childen,Smoker,REgion,Department,Jion_Data,Is_Manageer
0,1,John,28,M,55000.0,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,5.5,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,5.5,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,1.0,No,South,HR,2019-08-25,False

In [13]:
data_set["Childen"]=data_set["Childen"].fillna(data_set["Childen"].max())
print(data_set)

   ID   name  Age SEx   Salary  Childen Smoker REgion Department   Jion_Data  \
0   1   John   28   M  55000.0      2.0    Yes  North      Sales  2020-01-15
1   2   Jane   34   F  62000.0      1.0     No  South  Marketing  2019-06-23
2   3    Bob   45   M  70000.0      3.0    Yes   East         IT  2015-09-10
3   4  Alice   29   F  58000.0      0.0     No   West         HR  2021-03-12
4   5   Mike   38   M  65000.0      3.0    Yes  North    Finance  2018-12-01
5   6  Linda   31   F  60000.0      2.0     No  South         IT  2020-07-08
6   7  Steve   42   M  72000.0      1.0    Yes   East  Marketing  2016-11-20
7   8  Karen   36   F      NaN      2.0     No   West      Sales  2017-04-30
8   9    Tom   39   M  68000.0      3.0    Yes  North    Finance  2015-05-14
9  10  Susan   33   F  61000.0      1.0     No  South         HR  2019-08-25

   Is_Manageer
0        False
1         True
2        False
3        False
4         True
5        False
6         True
7        False
8        False
9        False

In [14]:
d1["Salary"]=d1["Salary"].fillna(d1["Salary"].mean())
print(d1)

KeyError: 'Salary'

In [ ]:
d1

<bound method NDFrame.copy of    ID   name  Age SEx  Salary  Childen Smoker REgion Department   Jion_Data  \
0  28   John   28   M     2.0      2.0    Yes  North      Sales  2020-01-15
1  34   Jane   34   F     1.0      1.0     No  South  Marketing  2019-06-23
2  45    Bob   45   M     3.0      3.0    Yes   East         IT  2015-09-10
3  29  Alice   29   F     0.0      0.0     No   West         HR  2021-03-12
4  38   Mike   38   M     3.0      3.0    Yes  North    Finance  2018-12-01
5  31  Linda   31   F     2.0      2.0     No  South         IT  2020-07-08
6  42  Steve   42   M     1.0      1.0    Yes   East  Marketing  2016-11-20
7  36  Karen   36   F     2.0      2.0     No   West      Sales  2017-04-30
8  39    Tom   39   M     3.0      3.0    Yes  North    Finance  2015-05-14
9  33  Susan   33   F     1.0      1.0     No  South         HR  2019-08-25

   Is_Manageer
0        False
1         True
2        False
3        False
4         True
5        False
6         True
7        False
8        False
9        False  >

In [ ]:
d2["Salary"] = d2["Salary"].fillna(d2["Salary"].mean())
print(d2)

   ID   name  Age SEx        Salary  Childen Smoker REgion Department  \
0   1   John   28   M  55000.000000      2.0    Yes  North      Sales
1   2   Jane   34   F  62000.000000      1.0     No  South  Marketing
2   3    Bob   45   M  70000.000000      3.0    Yes   East         IT
3   4  Alice   29   F  58000.000000      0.0     No   West         HR
4   5   Mike   38   M  65000.000000      3.0    Yes  North    Finance
5   6  Linda   31   F  60000.000000      2.0     No  South         IT
6   7  Steve   42   M  72000.000000      1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444      2.0     No   West      Sales
8   9    Tom   39   M  68000.000000      3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000      1.0     No  South         HR

    Jion_Data  Is_Manageer
0  2020-01-15        False
1  2019-06-23         True
2  2015-09-10        False
3  2021-03-12        False
4  2018-12-01         True
5  2020-07-08        False
6  2016-11-20         True
7  2017-04-30        False
8  2015-05-14        False
9  2019-08-25        False

In [ ]:
data_set

,ID,name,Age,SEx,Salary,Childen,Smoker,REgion,Department,Jion_Data,Is_Manageer
0,1,John,28,M,55000.0,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,3.0,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,1.0,No,South,HR,2019-08-25,False

In [ ]:
print(d1.head(3))

   ID  name  Age SEx   Salary  Childen Smoker REgion Department   Jion_Data  \
0   1  John   28   M  55000.0      2.0    Yes  North      Sales  2020-01-15
1   2  Jane   34   F  62000.0      1.0     No  South  Marketing  2019-06-23
2   3   Bob   45   M  70000.0      3.0    Yes   East         IT  2015-09-10

   Is_Manageer
0        False
1         True
2        False

In [ ]:
print(d1.head(5))

   ID   name  Age SEx   Salary  Childen Smoker REgion Department   Jion_Data  \
0   1   John   28   M  55000.0      2.0    Yes  North      Sales  2020-01-15
1   2   Jane   34   F  62000.0      1.0     No  South  Marketing  2019-06-23
2   3    Bob   45   M  70000.0      3.0    Yes   East         IT  2015-09-10
3   4  Alice   29   F  58000.0      0.0     No   West         HR  2021-03-12
4   5   Mike   38   M  65000.0      3.0    Yes  North    Finance  2018-12-01

   Is_Manageer
0        False
1         True
2        False
3        False
4         True

In [ ]:
print(d1.head(8))

   ID   name  Age SEx        Salary  Childen Smoker REgion Department  \
0   1   John   28   M  55000.000000      2.0    Yes  North      Sales
1   2   Jane   34   F  62000.000000      1.0     No  South  Marketing
2   3    Bob   45   M  70000.000000      3.0    Yes   East         IT
3   4  Alice   29   F  58000.000000      0.0     No   West         HR
4   5   Mike   38   M  65000.000000      3.0    Yes  North    Finance
5   6  Linda   31   F  60000.000000      2.0     No  South         IT
6   7  Steve   42   M  72000.000000      1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444      2.0     No   West      Sales

    Jion_Data  Is_Manageer
0  2020-01-15        False
1  2019-06-23         True
2  2015-09-10        False
3  2021-03-12        False
4  2018-12-01         True
5  2020-07-08        False
6  2016-11-20         True
7  2017-04-30        False

In [ ]:
print(d1.tail(5))

   ID   name  Age SEx        Salary  Childen Smoker REgion Department  \
5   6  Linda   31   F  60000.000000      2.0     No  South         IT
6   7  Steve   42   M  72000.000000      1.0    Yes   East  Marketing
7   8  Karen   36   F  63444.444444      2.0     No   West      Sales
8   9    Tom   39   M  68000.000000      3.0    Yes  North    Finance
9  10  Susan   33   F  61000.000000      1.0     No  South         HR

    Jion_Data  Is_Manageer
5  2020-07-08        False
6  2016-11-20         True
7  2017-04-30        False
8  2015-05-14        False
9  2019-08-25        False

In [ ]:
print(d1.tail(3))

   id   name  age sex   salary   bmi  children smoker region department  \
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [ ]:
print(d2.columns)

Index(['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker',
       'region', 'department', 'join_date', 'is_manager'],
      dtype='str')

In [ ]:
#column ar nam dheka 
print(d1.columns)

Index(['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker',
       'region', 'department', 'join_date', 'is_manager'],
      dtype='str')

In [ ]:
print(list(d1.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [ ]:
print(list(d2.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [ ]:
print(d1.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     str
 2   age         10 non-null     int64
 3   sex         10 non-null     str
 4   salary      9 non-null      float64
 5   bmi         10 non-null     float64
 6   children    9 non-null      float64
 7   smoker      10 non-null     str
 8   region      10 non-null     str
 9   department  10 non-null     str
 10  join_date   10 non-null     str
 11  is_manager  10 non-null     bool
dtypes: bool(1), float64(3), int64(2), str(6)
memory usage: 1018.0 bytes
None

In [ ]:
# data set a row and columns dhekar jonnu 
print(d1.shape)

(10, 12)

In [ ]:
#data set a datatypes dhekar jonnu dtyopes use kora hoi
print(d1.dtypes)

id              int64
name              str
age             int64
sex               str
salary        float64
bmi           float64
children      float64
smoker            str
region            str
department        str
join_date         str
is_manager       bool
dtype: object

In [ ]:
# data set ar describe
print(d1.describe())

             id        age        salary        bmi  children
count  10.00000  10.000000      9.000000  10.000000  9.000000
mean    5.50000  35.500000  63444.444444  25.140000  1.666667
std     3.02765   5.562773   5703.312877   2.620093  1.000000
min     1.00000  28.000000  55000.000000  21.900000  0.000000
25%     3.25000  31.500000  60000.000000  23.100000  1.000000
50%     5.50000  35.000000  62000.000000  24.700000  2.000000
75%     7.75000  38.750000  68000.000000  27.475000  2.000000
max    10.00000  45.000000  72000.000000  29.100000  3.000000

In [ ]:
#data frame ar index dheka 
print(d1.index)

RangeIndex(start=0, stop=10, step=1)

In [ ]:
#dataset ar value dheka 
print(d1.values)

[[1 'John' 28 'M' 55000.0 24.5 2.0 'Yes' 'North' 'Sales' '2020-01-15'
  False]
 [2 'Jane' 34 'F' 62000.0 22.1 1.0 'No' 'South' 'Marketing' '2019-06-23'
  True]
 [3 'Bob' 45 'M' 70000.0 27.8 3.0 'Yes' 'East' 'IT' '2015-09-10' False]
 [4 'Alice' 29 'F' 58000.0 23.4 0.0 'No' 'West' 'HR' '2021-03-12' False]
 [5 'Mike' 38 'M' 65000.0 28.2 nan 'Yes' 'North' 'Finance' '2018-12-01'
  True]
 [6 'Linda' 31 'F' 60000.0 21.9 2.0 'No' 'South' 'IT' '2020-07-08' False]
 [7 'Steve' 42 'M' 72000.0 26.5 1.0 'Yes' 'East' 'Marketing' '2016-11-20'
  True]
 [8 'Karen' 36 'F' nan 24.9 2.0 'No' 'West' 'Sales' '2017-04-30' False]
 [9 'Tom' 39 'M' 68000.0 29.1 3.0 'Yes' 'North' 'Finance' '2015-05-14'
  False]
 [10 'Susan' 33 'F' 61000.0 23.0 1.0 'No' 'South' 'HR' '2019-08-25' False]]

In [ ]:
#শুধু নির্দিষ্ট টাইপের কলাম দেখতে চাও
print(d1.select_dtypes(include=object))

    name sex smoker region department   join_date
0   John   M    Yes  North      Sales  2020-01-15
1   Jane   F     No  South  Marketing  2019-06-23
2    Bob   M    Yes   East         IT  2015-09-10
3  Alice   F     No   West         HR  2021-03-12
4   Mike   M    Yes  North    Finance  2018-12-01
5  Linda   F     No  South         IT  2020-07-08
6  Steve   M    Yes   East  Marketing  2016-11-20
7  Karen   F     No   West      Sales  2017-04-30
8    Tom   M    Yes  North    Finance  2015-05-14
9  Susan   F     No  South         HR  2019-08-25

C:\Users\Nado Jahan\AppData\Local\Temp\ipykernel_16500\378734865.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(d1.select_dtypes(include=object))

In [ ]:
print(d1.select_dtypes(include='Float64'))

    salary   bmi  children
0  55000.0  24.5       2.0
1  62000.0  22.1       1.0
2  70000.0  27.8       3.0
3  58000.0  23.4       0.0
4  65000.0  28.2       NaN
5  60000.0  21.9       2.0
6  72000.0  26.5       1.0
7      NaN  24.9       2.0
8  68000.0  29.1       3.0
9  61000.0  23.0       1.0

In [ ]:
print(d1.select_dtypes(include='int16'))

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#transpose করে (row ↔ column)
print(d1.T)

                     0           1           2           3           4  \
id                   1           2           3           4           5
name              John        Jane         Bob       Alice        Mike
age                 28          34          45          29          38
sex                  M           F           M           F           M
salary         55000.0     62000.0     70000.0     58000.0     65000.0
bmi               24.5        22.1        27.8        23.4        28.2
children           2.0         1.0         3.0         0.0         NaN
smoker             Yes          No         Yes          No         Yes
region           North       South        East        West       North
department       Sales   Marketing          IT          HR     Finance
join_date   2020-01-15  2019-06-23  2015-09-10  2021-03-12  2018-12-01
is_manager       False        True       False       False        True

                     5           6           7           8           9
id                   6           7           8           9          10
name             Linda       Steve       Karen         Tom       Susan
age                 31          42          36          39          33
sex                  F           M           F           M           F
salary         60000.0     72000.0         NaN     68000.0     61000.0
bmi               21.9        26.5        24.9        29.1        23.0
children           2.0         1.0         2.0         3.0         1.0
smoker              No         Yes          No         Yes          No
region           South        East        West       North       South
department          IT   Marketing       Sales     Finance          HR
join_date   2020-07-08  2016-11-20  2017-04-30  2015-05-14  2019-08-25
is_manager       False        True       False       False       False

In [ ]:
#মোট element (row × column) সংখ্যা
print(d1.size)

120

In [ ]:

#ডেটাফ্রেমের dimension (2 হলে 2D)
print(d1.ndim)

2

In [ ]:
#প্রতিটি কলামে কত memory লাগছে তা দেখায়
print(d1.memory_usage())

Index         128
id             80
name           80
age            80
sex            80
salary         80
bmi            80
children       80
smoker         80
region         80
department     80
join_date      80
is_manager     10
dtype: int64

In [ ]:
#র‍্যান্ডম রো দেখায়
print(d1.sample())

   id  name  age sex   salary   bmi  children smoker region department  \
0   1  John   28   M  55000.0  24.5       2.0    Yes  North      Sales

    join_date  is_manager
0  2020-01-15       False

In [ ]:
print(d1.sample())

   id  name  age sex   salary   bmi  children smoker region department  \
1   2  Jane   34   F  62000.0  22.1       1.0     No  South  Marketing

    join_date  is_manager
1  2019-06-23        True

In [ ]:
#কোন মান NaN তা True/False আকারে দেয়
print(d1.isnull())

      id   name    age    sex  salary    bmi  children  smoker  region  \
0  False  False  False  False   False  False     False   False   False
1  False  False  False  False   False  False     False   False   False
2  False  False  False  False   False  False     False   False   False
3  False  False  False  False   False  False     False   False   False
4  False  False  False  False   False  False      True   False   False
5  False  False  False  False   False  False     False   False   False
6  False  False  False  False   False  False     False   False   False
7  False  False  False  False    True  False     False   False   False
8  False  False  False  False   False  False     False   False   False
9  False  False  False  False   False  False     False   False   False

   department  join_date  is_manager
0       False      False       False
1       False      False       False
2       False      False       False
3       False      False       False
4       False      False       False
5       False      False       False
6       False      False       False
7       False      False       False
8       False      False       False
9       False      False       False

In [ ]:
#Missing না হলে True দেয়
print(d1.notnull())

     id  name   age   sex  salary   bmi  children  smoker  region  department  \
0  True  True  True  True    True  True      True    True    True        True
1  True  True  True  True    True  True      True    True    True        True
2  True  True  True  True    True  True      True    True    True        True
3  True  True  True  True    True  True      True    True    True        True
4  True  True  True  True    True  True     False    True    True        True
5  True  True  True  True    True  True      True    True    True        True
6  True  True  True  True    True  True      True    True    True        True
7  True  True  True  True   False  True      True    True    True        True
8  True  True  True  True    True  True      True    True    True        True
9  True  True  True  True    True  True      True    True    True        True

   join_date  is_manager
0       True        True
1       True        True
2       True        True
3       True        True
4       True        True
5       True        True
6       True        True
7       True        True
8       True        True
9       True        True

In [ ]:
#প্রতিটি কলামে unique মানের সংখ্যা
print(d1.)

In [15]:
#Duplicate রো চেক করে
print(d1.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [16]:
d1

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,5,Mike,38,M,65000.0,28.2,NaN,Yes,North,Finance,2018-12-01,True
5,6,Linda,31,F,60000.0,21.9,2.0,No,South,IT,2020-07-08,False
6,7,Steve,42,M,72000.0,26.5,1.0,Yes,East,Marketing,2016-11-20,True
7,8,Karen,36,F,NaN,24.9,2.0,No,West,Sales,2017-04-30,False
8,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
9,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [17]:
#Duplicate রো বাদ দেয়
print(d1.drop_duplicates())

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [ ]:
#Numeric কলামগুলোর মধ্যে correlation দেখায় #কোরিলেশনের মান সাধারণত -১ থেকে +১ এর মধ্যে থাকে:
#imp 
numaric_dataset1=d1.select_dtypes(include='number')
print(numaric_dataset1.corr())

                id       age    salary       bmi  children
id        1.000000  0.221007  0.357379  0.168080  0.064984
age       0.221007  1.000000  0.967111  0.732610  0.486310
salary    0.357379  0.967111  1.000000  0.690698  0.371964
bmi       0.168080  0.732610  0.690698  1.000000  0.636279
children  0.064984  0.486310  0.371964  0.636279  1.000000

In [25]:
#নির্দিষ্ট কলামে sort করে
print(d1.sort_values('age'))

   id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT

    join_date  is_manager
0  2020-01-15       False
3  2021-03-12       False
5  2020-07-08       False
9  2019-08-25       False
1  2019-06-23        True
7  2017-04-30       False
4  2018-12-01        True
8  2015-05-14       False
6  2016-11-20        True
2  2015-09-10       False

In [26]:
#কলাম rename করে
print(d1.rename(columns=({'name':'Name','age':'Age'})))

   id   Name  Age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [31]:
print(d1.rename(columns=({'salary':'Salary','bmi':'Bmi'}),inplace=True))

None

In [33]:
print(d1.sort_values('Bmi'))

   id   name  age sex   Salary   Bmi  children smoker region department  \
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance

    join_date  is_manager
5  2020-07-08       False
1  2019-06-23        True
9  2019-08-25       False
3  2021-03-12       False
0  2020-01-15       False
7  2017-04-30       False
6  2016-11-20        True
2  2015-09-10       False
4  2018-12-01        True
8  2015-05-14       False

In [34]:
#কলাম বা রো বাদ দেয়
print(d1.drop(columns='Bmi'))

   id   name  age sex   Salary  children smoker region department   join_date  \
0   1   John   28   M  55000.0       2.0    Yes  North      Sales  2020-01-15
1   2   Jane   34   F  62000.0       1.0     No  South  Marketing  2019-06-23
2   3    Bob   45   M  70000.0       3.0    Yes   East         IT  2015-09-10
3   4  Alice   29   F  58000.0       0.0     No   West         HR  2021-03-12
4   5   Mike   38   M  65000.0       NaN    Yes  North    Finance  2018-12-01
5   6  Linda   31   F  60000.0       2.0     No  South         IT  2020-07-08
6   7  Steve   42   M  72000.0       1.0    Yes   East  Marketing  2016-11-20
7   8  Karen   36   F      NaN       2.0     No   West      Sales  2017-04-30
8   9    Tom   39   M  68000.0       3.0    Yes  North    Finance  2015-05-14
9  10  Susan   33   F  61000.0       1.0     No  South         HR  2019-08-25

   is_manager
0       False
1        True
2       False
3       False
4        True
5       False
6        True
7       False
8       False
9       False

In [37]:
#কলাম বা রো বাদ দেয়
print(d1.drop('sex',axis=1))

   id   name  age   Salary   Bmi  children smoker region department  \
0   1   John   28  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [39]:
print(d1.drop('is_manager',axis=1))

   id   name  age sex   Salary   Bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date
0  2020-01-15
1  2019-06-23
2  2015-09-10
3  2021-03-12
4  2018-12-01
5  2020-07-08
6  2016-11-20
7  2017-04-30
8  2015-05-14
9  2019-08-25

In [40]:
#নতুন index সেট করে
print(d1.reset_index())

   index  id   name  age sex   Salary   Bmi  children smoker region  \
0      0   1   John   28   M  55000.0  24.5       2.0    Yes  North
1      1   2   Jane   34   F  62000.0  22.1       1.0     No  South
2      2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East
3      3   4  Alice   29   F  58000.0  23.4       0.0     No   West
4      4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North
5      5   6  Linda   31   F  60000.0  21.9       2.0     No  South
6      6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East
7      7   8  Karen   36   F      NaN  24.9       2.0     No   West
8      8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North
9      9  10  Susan   33   F  61000.0  23.0       1.0     No  South

  department   join_date  is_manager
0      Sales  2020-01-15       False
1  Marketing  2019-06-23        True
2         IT  2015-09-10       False
3         HR  2021-03-12       False
4    Finance  2018-12-01        True
5         IT  2020-07-08       False
6  Marketing  2016-11-20        True
7      Sales  2017-04-30       False
8    Finance  2015-05-14       False
9         HR  2019-08-25       False

In [42]:
#Group করে পরিসংখ্যান বের করে
print(d1.groupby('age')['Salary'].mean())

age
28    55000.0
29    58000.0
31    60000.0
33    61000.0
34    62000.0
36        NaN
38    65000.0
39    68000.0
42    72000.0
45    70000.0
Name: Salary, dtype: float64

In [ ]:
#df.apply()
#Custom function প্রয়োগ করে

In [43]:
#Missing value পূরণ করে
print(d1.fillna(3))

   id   name  age sex   Salary   Bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       3.0    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      3.0  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False

In [44]:
#Missing value বাদ দেয়
print(d1.dropna())

   id   name  age sex   Salary   Bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
5  2020-07-08       False
6  2016-11-20        True
8  2015-05-14       False
9  2019-08-25       False