In [72]:
import pandas as pd

In [73]:
Dataset=pd.read_csv("insurance (1).csv")
Dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [74]:
Dataset.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [75]:
Dataset.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [76]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [77]:
Dataset.shape

(1338, 7)

In [78]:
Dataset.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [79]:
Dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='str')

In [80]:
alldata=pd.DataFrame(Dataset,index=[60,44,55,55,88,66,87,55,33,1022])
alldata

      age     sex     bmi  children smoker     region      charges
60     43    male  27.360         3     no  northeast   8606.21740
44     38    male  37.050         1     no  northeast   6079.67150
55     58    male  36.955         2    yes  northwest  47496.49445
55     58    male  36.955         2    yes  northwest  47496.49445
88     46  female  27.740         0     no  northwest   8026.66660
66     61  female  39.100         2     no  southwest  14235.07200
87     56  female  27.200         0     no  southwest  11073.17600
55     58    male  36.955         2    yes  northwest  47496.49445
33     63    male  28.310         0     no  northwest  13770.09790
1022   47    male  36.080         1    yes  southeast  42211.13820

In [81]:
alldata.info()

<class 'pandas.DataFrame'>
Index: 10 entries, 60 to 1022
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       10 non-null     int64
 1   sex       10 non-null     str
 2   bmi       10 non-null     float64
 3   children  10 non-null     int64
 4   smoker    10 non-null     str
 5   region    10 non-null     str
 6   charges   10 non-null     float64
dtypes: float64(2), int64(2), str(3)
memory usage: 640.0 bytes

In [82]:
alldata.shape

(10, 7)

In [83]:
alldata.head()

    age     sex     bmi  children smoker     region      charges
60   43    male  27.360         3     no  northeast   8606.21740
44   38    male  37.050         1     no  northeast   6079.67150
55   58    male  36.955         2    yes  northwest  47496.49445
55   58    male  36.955         2    yes  northwest  47496.49445
88   46  female  27.740         0     no  northwest   8026.66660

In [84]:
alldata.tail()

      age     sex     bmi  children smoker     region      charges
66     61  female  39.100         2     no  southwest  14235.07200
87     56  female  27.200         0     no  southwest  11073.17600
55     58    male  36.955         2    yes  northwest  47496.49445
33     63    male  28.310         0     no  northwest  13770.09790
1022   47    male  36.080         1    yes  southeast  42211.13820

In [85]:
#alldata=pd.DataFrame(Dataset,index=[21:33])
#alldata don't do this

In [86]:
Dataset[101:110]

     age     sex     bmi  children smoker     region      charges
101   30    male  25.460         0     no  northeast   3645.08940
102   18  female  30.115         0     no  northeast  21344.84670
103   61  female  29.920         3    yes  southeast  30942.19180
104   34  female  27.500         1     no  southwest   5003.85300
105   20    male  28.025         1    yes  northwest  17560.37975
106   19  female  28.400         1     no  southwest   2331.51900
107   26    male  30.875         2     no  northwest   3877.30425
108   29    male  27.940         0     no  southeast   2867.11960
109   63    male  35.090         0    yes  southeast  47055.53210

In [87]:
Dataset1=Dataset.copy()
Dataset2=Dataset.copy()
Dataset3=Dataset.copy()

In [88]:
#column Rename
Dataset1.rename({'Age':'boyos','Sex':'jander','Bmi':'bmi','children':'shosi'},axis=1,inplace=True)
Dataset1

      age     sex     bmi  shosi smoker     region      charges
0      19  female  27.900      0    yes  southwest  16884.92400
1      18    male  33.770      1     no  southeast   1725.55230
2      28    male  33.000      3     no  southeast   4449.46200
3      33    male  22.705      0     no  northwest  21984.47061
4      32    male  28.880      0     no  northwest   3866.85520
...   ...     ...     ...    ...    ...        ...          ...
1333   50    male  30.970      3     no  northwest  10600.54830
1334   18  female  31.920      0     no  northeast   2205.98080
1335   18  female  36.850      0     no  southeast   1629.83350
1336   21  female  25.800      0     no  southwest   2007.94500
1337   61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [89]:
Dataset1

      age     sex     bmi  shosi smoker     region      charges
0      19  female  27.900      0    yes  southwest  16884.92400
1      18    male  33.770      1     no  southeast   1725.55230
2      28    male  33.000      3     no  southeast   4449.46200
3      33    male  22.705      0     no  northwest  21984.47061
4      32    male  28.880      0     no  northwest   3866.85520
...   ...     ...     ...    ...    ...        ...          ...
1333   50    male  30.970      3     no  northwest  10600.54830
1334   18  female  31.920      0     no  northeast   2205.98080
1335   18  female  36.850      0     no  southeast   1629.83350
1336   21  female  25.800      0     no  southwest   2007.94500
1337   61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [90]:
Dataset1['region'][52:66]

52    southwest
53    southeast
54    northwest
55    northwest
56    northeast
57    southeast
58    southeast
59    northwest
60    northeast
61    southeast
62    northwest
63    northwest
64    northwest
65    southwest
Name: region, dtype: str

In [ ]:
Dataset1['age']=Dataset1['age'].astype(str,errors='ignore')
print(Dataset1)

     age     sex     bmi  shosi smoker     region      charges
0     19  female  27.900      0    yes  southwest  16884.92400
1     18    male  33.770      1     no  southeast   1725.55230
2     28    male  33.000      3     no  southeast   4449.46200
3     33    male  22.705      0     no  northwest  21984.47061
4     32    male  28.880      0     no  northwest   3866.85520
...   ..     ...     ...    ...    ...        ...          ...
1333  50    male  30.970      3     no  northwest  10600.54830
1334  18  female  31.920      0     no  northeast   2205.98080
1335  18  female  36.850      0     no  southeast   1629.83350
1336  21  female  25.800      0     no  southwest   2007.94500
1337  61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
Dataset1['age']=Dataset1['age'].astype(int,errors='ignore')
print(Dataset1)

      age     sex     bmi  shosi smoker     region      charges
0      19  female  27.900      0    yes  southwest  16884.92400
1      18    male  33.770      1     no  southeast   1725.55230
2      28    male  33.000      3     no  southeast   4449.46200
3      33    male  22.705      0     no  northwest  21984.47061
4      32    male  28.880      0     no  northwest   3866.85520
...   ...     ...     ...    ...    ...        ...          ...
1333   50    male  30.970      3     no  northwest  10600.54830
1334   18  female  31.920      0     no  northeast   2205.98080
1335   18  female  36.850      0     no  southeast   1629.83350
1336   21  female  25.800      0     no  southwest   2007.94500
1337   61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
Dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      1338 non-null   int64
 1   sex      1338 non-null   str
 2   bmi      1338 non-null   float64
 3   shosi    1338 non-null   int64
 4   smoker   1338 non-null   str
 5   region   1338 non-null   str
 6   charges  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [ ]:
Dataset1['bmi']=Dataset1['bmi'].astype(float,errors='ignore')
Dataset1

      age     sex     bmi  shosi smoker     region      charges
0      19  female  27.900      0    yes  southwest  16884.92400
1      18    male  33.770      1     no  southeast   1725.55230
2      28    male  33.000      3     no  southeast   4449.46200
3      33    male  22.705      0     no  northwest  21984.47061
4      32    male  28.880      0     no  northwest   3866.85520
...   ...     ...     ...    ...    ...        ...          ...
1333   50    male  30.970      3     no  northwest  10600.54830
1334   18  female  31.920      0     no  northeast   2205.98080
1335   18  female  36.850      0     no  southeast   1629.83350
1336   21  female  25.800      0     no  southwest   2007.94500
1337   61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
Dataset1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age      1338 non-null   int64
 1   sex      1338 non-null   str
 2   bmi      1338 non-null   float64
 3   shosi    1338 non-null   int64
 4   smoker   1338 non-null   str
 5   region   1338 non-null   str
 6   charges  1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [91]:
Dataset1['sex']=Dataset1['sex'].astype('category')
Dataset1

      age     sex     bmi  shosi smoker     region      charges
0      19  female  27.900      0    yes  southwest  16884.92400
1      18    male  33.770      1     no  southeast   1725.55230
2      28    male  33.000      3     no  southeast   4449.46200
3      33    male  22.705      0     no  northwest  21984.47061
4      32    male  28.880      0     no  northwest   3866.85520
...   ...     ...     ...    ...    ...        ...          ...
1333   50    male  30.970      3     no  northwest  10600.54830
1334   18  female  31.920      0     no  northeast   2205.98080
1335   18  female  36.850      0     no  southeast   1629.83350
1336   21  female  25.800      0     no  southwest   2007.94500
1337   61  female  29.070      0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
Dataset1.info()
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       1338 non-null   int64
 1   Sex       1338 non-null   category
 2   Bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: category(1), float64(2), int64(2), str(2)
memory usage: 64.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [ ]:
Dataset1['Sex']=Dataset1['Sex'].astype(str,errors='ignore')
Dataset1

      Age     Sex     Bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
top=Dataset1.head()
bortom=Dataset1.tail()
random=Dataset1[39:55]

a_new_dataset=pd.concat([top,bortom,random],ignore_index=True)
print(a_new_dataset)

    Age     Sex     Bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
5    50    male  30.970         3     no  northwest  10600.54830
6    18  female  31.920         0     no  northeast   2205.98080
7    18  female  36.850         0     no  southeast   1629.83350
8    21  female  25.800         0     no  southwest   2007.94500
9    61  female  29.070         0    yes  northwest  29141.36030
10   60    male  39.900         0    yes  southwest  48173.36100
11   24  female  26.600         0     no  northeast   3046.06200
12   31  female  36.630         2     no  southeast   4949.75870
13   41    male  21.780         1     no  southeast   6272.47720
14   37  female  30.800         2     no  southeast   6313.75900
15   38    male  37.050         1     no  northeast   6079.67150
16   55    male  37.300         0     no  southwest  20630.28351
17   18  female  38.665         2     no  northeast   3393.35635
18   28  female  34.770         0     no  northwest   3556.92230
19   60  female  24.530         0     no  southeast  12629.89670
20   36    male  35.200         1    yes  southeast  38709.17600
21   18  female  35.625         0     no  northeast   2211.13075
22   21  female  33.630         2     no  northwest   3579.82870
23   48    male  28.000         1    yes  southwest  23568.27200
24   36    male  34.430         0    yes  southeast  37742.57570
25   40  female  28.690         3     no  northwest   8059.67910

In [ ]:
change_battom=Dataset2.tail(2).rename(columns={
    'age':'Age',
    'sex':'Sex',
    'bmi':'Bmi',
    'children':'Chilren',
    'smoker':'smoker',
    'region':'Region',
    'charges':'Changes'


})
change_battom=change_battom.reset_index(drop=True)
change_top=Dataset2.head(2)
change_top=change_top.reset_index(drop=True)
change_center=Dataset2[1001:1003].rename(columns={
    'age':'Age',
    'sex':'Sex',
    'bmi':'Bmi',
    'childen':'Chilren',
    'Smoker':'SMOKER',
    'Region':'REGION'
    
})
change_center=change_center.reset_index(drop=True)
a_new_set_dataset2=pd.concat([change_battom,change_top,change_center],axis=1)
print(a_new_set_dataset2)

   Age     Sex    Bmi  Chilren smoker     Region     Changes  age     sex  \
0   21  female  25.80        0     no  southwest   2007.9450   19  female
1   61  female  29.07        0    yes  northwest  29141.3603   18    male

     bmi  ...  smoker     region     charges  Age   Sex   Bmi  children  \
0  27.90  ...     yes  southwest  16884.9240   24  male  32.7         0
1  33.77  ...      no  southeast   1725.5523   24  male  25.8         0

   smoker     region    charges
0     yes  southwest  34472.841
1      no  southwest   1972.950

[2 rows x 21 columns]

In [ ]:
change_battom=change_battom.reset_index(drop=True)
change_battom

NameError: name 'change_battom' is not defined

In [ ]:
change_bottom = Dataset2.tail(2).rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
    'Charges':'CHARGES'
    })
change_bottom = change_bottom.reset_index(drop=True)
change_top = Dataset2.head(2)
change_top = change_top.reset_index(drop=True)
change_center = Dataset2[1001:1003].rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
})
change_center = change_center.reset_index(drop=True)
b_new_set = pd.concat([change_bottom, change_top, change_center], axis=1)
print(b_new_set)

   age     sex    bmi  children smoker     region     charges  age     sex  \
0   21  female  25.80         0     no  southwest   2007.9450   19  female
1   61  female  29.07         0    yes  northwest  29141.3603   18    male

     bmi  ...  smoker     region     charges  age   sex   bmi  children  \
0  27.90  ...     yes  southwest  16884.9240   24  male  32.7         0
1  33.77  ...      no  southeast   1725.5523   24  male  25.8         0

   smoker     region    charges
0     yes  southwest  34472.841
1      no  southwest   1972.950

[2 rows x 21 columns]

In [ ]:
import numpy as np
randomly =np.random.rand(10,8)
for i in (np.random.choice(8,3)):
    print(i)

4
7
1

In [ ]:
import pandas as pd
import numpy as np
random_col=np.random.rand(10,6)
for i in range(random_col.shape[1]):
    nan_value=np.random.choice(5,3, replace=False)
    random_col[nan_value,i]=np.nan
    
    data_f=pd.DataFrame(random_col)
print(data_f)

          0         1         2         3         4         5
0       NaN  0.191983       NaN       NaN       NaN       NaN
1  0.438171       NaN       NaN  0.449235       NaN       NaN
2       NaN       NaN  0.112868       NaN  0.745931       NaN
3  0.097373  0.177525       NaN  0.961226       NaN  0.614772
4       NaN       NaN  0.026676       NaN  0.157416  0.308691
5  0.390608  0.311601  0.999705  0.934643  0.266028  0.430569
6  0.289238  0.607578  0.706804  0.865791  0.677310  0.735141
7  0.467198  0.066383  0.207060  0.640625  0.272694  0.209635
8  0.083053  0.905273  0.703854  0.923621  0.090211  0.621837
9  0.115649  0.735651  0.811435  0.429823  0.757650  0.056488

In [ ]:
data_f.columns=['col1','col2','col3','col4','col5','col6']
print(data_f)

       col1      col2      col3      col4      col5      col6
0       NaN  0.191983       NaN       NaN       NaN       NaN
1  0.438171       NaN       NaN  0.449235       NaN       NaN
2       NaN       NaN  0.112868       NaN  0.745931       NaN
3  0.097373  0.177525       NaN  0.961226       NaN  0.614772
4       NaN       NaN  0.026676       NaN  0.157416  0.308691
5  0.390608  0.311601  0.999705  0.934643  0.266028  0.430569
6  0.289238  0.607578  0.706804  0.865791  0.677310  0.735141
7  0.467198  0.066383  0.207060  0.640625  0.272694  0.209635
8  0.083053  0.905273  0.703854  0.923621  0.090211  0.621837
9  0.115649  0.735651  0.811435  0.429823  0.757650  0.056488

In [ ]:
data_f.columns=['col1','col2','col3','col4','col5','col6']
print(data_f)

       col1      col2      col3      col4      col5      col6
0       NaN  0.191983       NaN       NaN       NaN       NaN
1  0.438171       NaN       NaN  0.449235       NaN       NaN
2       NaN       NaN  0.112868       NaN  0.745931       NaN
3  0.097373  0.177525       NaN  0.961226       NaN  0.614772
4       NaN       NaN  0.026676       NaN  0.157416  0.308691
5  0.390608  0.311601  0.999705  0.934643  0.266028  0.430569
6  0.289238  0.607578  0.706804  0.865791  0.677310  0.735141
7  0.467198  0.066383  0.207060  0.640625  0.272694  0.209635
8  0.083053  0.905273  0.703854  0.923621  0.090211  0.621837
9  0.115649  0.735651  0.811435  0.429823  0.757650  0.056488

In [ ]:
import numpy as np
import pandas as pd
colums=np.random.randint(1,100,size=(5,4)).astype(float)#numpy np.nan =float...can't canvert float Nan to integer
for i in range(colums.shape[1]):
    random_n=np.random.choice(5,3,replace=True)
    colums[random_n,i]=np.nan
    data=pd.DataFrame(colums)
    data=data.fillna(0).astype(int)
print(data)

    0   1   2   3
0   0  10  27  79
1   0   0   0   0
2  81   0  28   0
3  55  52  82  51
4   0  27  24  14

In [ ]:
data.columns=['col1','col2','col3','col4']
print(data)

   col1  col2  col3  col4
0     0    10    27    79
1     0     0     0     0
2    81     0    28     0
3    55    52    82    51
4     0    27    24    14

In [ ]:
import numpy as np
individual=np.random.rand(7,5)
for i in range(individual.shape[1]):
    random_co=np.random.choice(5,2,replace=True)
    individual[random_co,i]=np.nan
    data_col=pd.DataFrame(individual)
print(data_col)

          0         1         2         3         4
0  0.354445  0.692931       NaN       NaN  0.087609
1       NaN  0.984009  0.699774  0.655078       NaN
2  0.997789       NaN  0.232457       NaN  0.145230
3  0.218225  0.294655       NaN  0.251805  0.262325
4  0.457729       NaN  0.330241  0.710488       NaN
5  0.129213  0.562924  0.023617  0.903944  0.787163
6  0.016984  0.741826  0.687919  0.422355  0.686252

In [ ]:
data_col

          0         1         2         3         4
0  0.354445  0.692931       NaN       NaN  0.087609
1       NaN  0.984009  0.699774  0.655078       NaN
2  0.997789       NaN  0.232457       NaN  0.145230
3  0.218225  0.294655       NaN  0.251805  0.262325
4  0.457729       NaN  0.330241  0.710488       NaN
5  0.129213  0.562924  0.023617  0.903944  0.787163
6  0.016984  0.741826  0.687919  0.422355  0.686252

In [ ]:
data_col.columns=['col1m','col2','col3','col4','col5']
print(data_col)

      col1m      col2      col3      col4      col5
0  0.354445  0.692931       NaN       NaN  0.087609
1       NaN  0.984009  0.699774  0.655078       NaN
2  0.997789       NaN  0.232457       NaN  0.145230
3  0.218225  0.294655       NaN  0.251805  0.262325
4  0.457729       NaN  0.330241  0.710488       NaN
5  0.129213  0.562924  0.023617  0.903944  0.787163
6  0.016984  0.741826  0.687919  0.422355  0.686252

In [ ]:
data1=data_col.copy()
data2=data_col.copy()
data3=data_col.copy()
data4=data_f.copy()
data5=data_f.copy()

In [ ]:
data_col.drop(['col4'],axis=1,inplace=True)
print(data_col)

      col1m      col5
0       NaN       NaN
1       NaN  0.920295
2  0.754577  0.620149
3  0.757293       NaN
4  0.954630  0.482095
5  0.665917  0.235486
6  0.751526  0.830302

In [ ]:
data_col=data_col.dropna()
print(data_col)

      col1m      col5
2  0.754577  0.620149
4  0.954630  0.482095
5  0.665917  0.235486
6  0.751526  0.830302

In [ ]:
data2.fillna(7,inplace=True)
print(data2)

      col1m      col5
2  0.754577  0.620149
4  0.954630  0.482095
5  0.665917  0.235486
6  0.751526  0.830302

In [ ]:
data4

          0         1         2         3         4         5
0       NaN       NaN  0.699890       NaN       NaN       NaN
1  0.630636       NaN       NaN       NaN       NaN       NaN
2  0.986600  0.265350  0.064257  0.379590  0.190329  0.122635
3       NaN       NaN       NaN  0.834280  0.444491  0.146508
4       NaN  0.172803       NaN       NaN       NaN       NaN
5  0.854893  0.374336  0.595688  0.140172  0.349751  0.745497
6  0.533897  0.725265  0.732975  0.420130  0.688743  0.464123
7  0.348019  0.747234  0.300503  0.016938  0.305826  0.999726
8  0.329990  0.303138  0.636794  0.729883  0.927715  0.685866
9  0.526647  0.647420  0.466934  0.875038  0.579971  0.183821

In [ ]:
data4.columns=['col1','col2','col3','col4','col5','col6']
print(data4)

       col1      col2      col3      col4      col5      col6
0       NaN       NaN  0.699890       NaN       NaN       NaN
1  0.630636       NaN       NaN       NaN       NaN       NaN
2  0.986600  0.265350  0.064257  0.379590  0.190329  0.122635
3       NaN       NaN       NaN  0.834280  0.444491  0.146508
4       NaN  0.172803       NaN       NaN       NaN       NaN
5  0.854893  0.374336  0.595688  0.140172  0.349751  0.745497
6  0.533897  0.725265  0.732975  0.420130  0.688743  0.464123
7  0.348019  0.747234  0.300503  0.016938  0.305826  0.999726
8  0.329990  0.303138  0.636794  0.729883  0.927715  0.685866
9  0.526647  0.647420  0.466934  0.875038  0.579971  0.183821

In [ ]:
data4['col1'] = data4['col5'].fillna(data4['col5'].max())
print(data4)

       col1      col2      col3      col4      col5      col6
0  0.927715       NaN  0.699890       NaN       NaN       NaN
1  0.927715       NaN       NaN       NaN       NaN       NaN
2  0.190329  0.265350  0.064257  0.379590  0.190329  0.122635
3  0.444491       NaN       NaN  0.834280  0.444491  0.146508
4  0.927715  0.172803       NaN       NaN       NaN       NaN
5  0.349751  0.374336  0.595688  0.140172  0.349751  0.745497
6  0.688743  0.725265  0.732975  0.420130  0.688743  0.464123
7  0.305826  0.747234  0.300503  0.016938  0.305826  0.999726
8  0.927715  0.303138  0.636794  0.729883  0.927715  0.685866
9  0.579971  0.647420  0.466934  0.875038  0.579971  0.183821

In [ ]:
data4['col3'] = data4['col3'].fillna(data4['col3'].max())
print(data4)

       col1      col2      col3      col4      col5      col6
0  0.927715       NaN  0.699890       NaN       NaN       NaN
1  0.927715       NaN  0.732975       NaN       NaN       NaN
2  0.190329  0.265350  0.064257  0.379590  0.190329  0.122635
3  0.444491       NaN  0.732975  0.834280  0.444491  0.146508
4  0.927715  0.172803  0.732975       NaN       NaN       NaN
5  0.349751  0.374336  0.595688  0.140172  0.349751  0.745497
6  0.688743  0.725265  0.732975  0.420130  0.688743  0.464123
7  0.305826  0.747234  0.300503  0.016938  0.305826  0.999726
8  0.927715  0.303138  0.636794  0.729883  0.927715  0.685866
9  0.579971  0.647420  0.466934  0.875038  0.579971  0.183821

In [ ]:
data4['col2']=data4['col4'].fillna(data4['col3'].mean())
print(data4)

       col1      col2      col3      col4      col5      col6
0  0.927715  0.569596  0.699890       NaN       NaN       NaN
1  0.927715  0.569596  0.732975       NaN       NaN       NaN
2  0.190329  0.379590  0.064257  0.379590  0.190329  0.122635
3  0.444491  0.834280  0.732975  0.834280  0.444491  0.146508
4  0.927715  0.569596  0.732975       NaN       NaN       NaN
5  0.349751  0.140172  0.595688  0.140172  0.349751  0.745497
6  0.688743  0.420130  0.732975  0.420130  0.688743  0.464123
7  0.305826  0.016938  0.300503  0.016938  0.305826  0.999726
8  0.927715  0.729883  0.636794  0.729883  0.927715  0.685866
9  0.579971  0.875038  0.466934  0.875038  0.579971  0.183821

In [ ]:
data4['col6']=data4['col4'].fillna(data4['col4'].max())
data4

       col1      col2      col3      col4      col5      col6
0  0.927715  0.569596  0.875038  0.875038       NaN  0.875038
1  0.927715  0.569596  0.875038  0.875038       NaN  0.875038
2  0.190329  0.379590  0.379590  0.379590  0.190329  0.379590
3  0.444491  0.834280  0.834280  0.834280  0.444491  0.834280
4  0.927715  0.569596  0.875038  0.875038       NaN  0.875038
5  0.349751  0.140172  0.140172  0.140172  0.349751  0.140172
6  0.688743  0.420130  0.420130  0.420130  0.688743  0.420130
7  0.305826  0.016938  0.016938  0.016938  0.305826  0.016938
8  0.927715  0.729883  0.729883  0.729883  0.927715  0.729883
9  0.579971  0.875038  0.875038  0.875038  0.579971  0.875038

In [ ]:
import pandas as pd
import numpy as np
dataset_1=np.random.rand(5,9)# 5row ,9 column
for i  in range(dataset_1.shape[1]):
    random_3=np.random.choice(5,3,replace=True)
    dataset_1[random_3,i]=np.nan#array[row_index, column_index]
    nsn_add=pd.DataFrame(dataset_1)
print(nsn_add)

          0         1         2         3         4         5         6  \
0  0.175303  0.398580       NaN       NaN       NaN       NaN  0.325879
1  0.388991  0.983673  0.924279  0.441798       NaN  0.853365  0.077370
2  0.989083       NaN       NaN       NaN  0.310080  0.981991       NaN
3       NaN       NaN       NaN       NaN  0.929733  0.241859       NaN
4       NaN  0.256012  0.365520  0.671060  0.487159       NaN       NaN

          7         8
0  0.840449  0.875120
1       NaN       NaN
2  0.350893       NaN
3       NaN  0.448790
4  0.143101  0.557621

In [ ]:
import pandas as pd 
import numpy as np
data_set1=np.random.rand(4,5)
for j in range(data_set1.shape[1]):# shape[0]=row,shape[1]=column
    da=np.random.choice(3,3,replace=False)
    data_set1[da,j]=np.nan
    data_d=pd.DataFrame(data_set1)
print(data_d)

          0         1         2         3         4
0       NaN  0.302281  0.347439  0.251714  0.703357
1       NaN  0.185283  0.111989  0.965131  0.627983
2       NaN  0.203295  0.815142  0.517156  0.665992
3  0.152133  0.358683  0.673936  0.867360  0.904423
          0         1         2         3         4
0       NaN       NaN  0.347439  0.251714  0.703357
1       NaN       NaN  0.111989  0.965131  0.627983
2       NaN       NaN  0.815142  0.517156  0.665992
3  0.152133  0.358683  0.673936  0.867360  0.904423
          0         1         2         3         4
0       NaN       NaN       NaN  0.251714  0.703357
1       NaN       NaN       NaN  0.965131  0.627983
2       NaN       NaN       NaN  0.517156  0.665992
3  0.152133  0.358683  0.673936  0.867360  0.904423
          0         1         2        3         4
0       NaN       NaN       NaN      NaN  0.703357
1       NaN       NaN       NaN      NaN  0.627983
2       NaN       NaN       NaN      NaN  0.665992
3  0.152133  0.358683  0.673936  0.86736  0.904423
          0         1         2        3         4
0       NaN       NaN       NaN      NaN       NaN
1       NaN       NaN       NaN      NaN       NaN
2       NaN       NaN       NaN      NaN       NaN
3  0.152133  0.358683  0.673936  0.86736  0.904423

In [ ]:
import pandas as pd 
import numpy as np
data_set2=data_set1.copy()
data_se=data_set1[3:5].copy()
for j in range(data_se.shape[1]):# shape[0]=row,shape[1]=column
    da=np.random.choice(data_se.shape[0],2,replace=True)
    da.iloc[da,j]=np.nan
    data_se.iloc[3:5]=np.nan#iloc: সংখ্যা বা পজিশন দিয়ে খোঁজে (যেমন: df.iloc[row_index, column_index])
    data_d.iloc=pd.DataFrame(data_se)#NumPy array-এর সাথে .iloc ব্যবহার করা যায় না। .iloc শুধুমাত্র Pandas DataFrame বা Series-এর জন্য কাজ করে। এখানে আপনার
print(data_d)

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

In [ ]:
data_set2=data_set1
print(data_set2)

[[       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan]
 [0.1521335  0.35868331 0.67393641 0.86736015 0.90442348]]

In [ ]:
import pandas as pd 
import numpy as np

# ১. ডেটা কপি করা
data_set2 = data_set1.copy()
data_se = data_set1[2:4].copy()

# ২. লুপ চালিয়ে নির্দিষ্ট কিছু ঘরে NaN বসানো
for j in range(data_se.shape[1]): # প্রতিটি কলামের জন্য
    # ৩টি র‍্যান্ডম সারির ইনডেক্স বেছে নেওয়া
    rows_to_nan = np.random.choice(data_se.shape[0], 3, replace=True)
    
    # .iloc ব্যবহার করে ঐ নির্দিষ্ট সারি ও কলামে NaN বসানো
    data_se[rows_to_nan, j] = np.nan

# ৩. মূল ডেটাসেটের নির্দিষ্ট অংশে এই পরিবর্তিত ডেটা বসানো
data_set2[2:4] = data_se

# ৪. ফলাফল প্রিন্ট করা
print(data_set2[3:5]) # পরিবর্তন দেখার জন্য ৬০-৭৫ সারি প্রিন্ট

[[nan nan nan nan nan]]

In [ ]:
d=data5.info()
print(d)

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    7 non-null      float64
 1   col2    7 non-null      float64
 2   col3    7 non-null      float64
 3   col4    7 non-null      float64
 4   col5    7 non-null      float64
 5   col6    7 non-null      float64
dtypes: float64(6)
memory usage: 608.0 bytes
None