In [2]:
import pandas as pd

In [3]:
df=pd.read_json("practice_dataset1.json")

In [14]:
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()
d6=df.copy()

In [8]:
#DataFrame-এর সব value কে numpy array আকারে দেখাও।
print(df.to_numpy)

<bound method DataFrame.to_numpy of    id   name  age sex   salary   bmi  children smoker region department  \
0   1   John   28   M  55000.0  24.5       2.0    Yes  North      Sales
1   2   Jane   34   F  62000.0  22.1       1.0     No  South  Marketing
2   3    Bob   45   M  70000.0  27.8       3.0    Yes   East         IT
3   4  Alice   29   F  58000.0  23.4       0.0     No   West         HR
4   5   Mike   38   M  65000.0  28.2       NaN    Yes  North    Finance
5   6  Linda   31   F  60000.0  21.9       2.0     No  South         IT
6   7  Steve   42   M  72000.0  26.5       1.0    Yes   East  Marketing
7   8  Karen   36   F      NaN  24.9       2.0     No   West      Sales
8   9    Tom   39   M  68000.0  29.1       3.0    Yes  North    Finance
9  10  Susan   33   F  61000.0  23.0       1.0     No  South         HR

    join_date  is_manager
0  2020-01-15       False
1  2019-06-23        True
2  2015-09-10       False
3  2021-03-12       False
4  2018-12-01        True
5  2020-07-08       False
6  2016-11-20        True
7  2017-04-30       False
8  2015-05-14       False
9  2019-08-25       False  >

In [ ]:
print(df.values)#old ata

[[1 'John' 28 'M' 55000.0 24.5 2.0 'Yes' 'North' 'Sales' '2020-01-15'
  False]
 [2 'Jane' 34 'F' 62000.0 22.1 1.0 'No' 'South' 'Marketing' '2019-06-23'
  True]
 [3 'Bob' 45 'M' 70000.0 27.8 3.0 'Yes' 'East' 'IT' '2015-09-10' False]
 [4 'Alice' 29 'F' 58000.0 23.4 0.0 'No' 'West' 'HR' '2021-03-12' False]
 [5 'Mike' 38 'M' 65000.0 28.2 nan 'Yes' 'North' 'Finance' '2018-12-01'
  True]
 [6 'Linda' 31 'F' 60000.0 21.9 2.0 'No' 'South' 'IT' '2020-07-08' False]
 [7 'Steve' 42 'M' 72000.0 26.5 1.0 'Yes' 'East' 'Marketing' '2016-11-20'
  True]
 [8 'Karen' 36 'F' nan 24.9 2.0 'No' 'West' 'Sales' '2017-04-30' False]
 [9 'Tom' 39 'M' 68000.0 29.1 3.0 'Yes' 'North' 'Finance' '2015-05-14'
  False]
 [10 'Susan' 33 'F' 61000.0 23.0 1.0 'No' 'South' 'HR' '2019-08-25' False]]

In [12]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     str
 2   age         10 non-null     int64
 3   sex         10 non-null     str
 4   salary      9 non-null      float64
 5   bmi         10 non-null     float64
 6   children    9 non-null      float64
 7   smoker      10 non-null     str
 8   region      10 non-null     str
 9   department  10 non-null     str
 10  join_date   10 non-null     str
 11  is_manager  10 non-null     bool
dtypes: bool(1), float64(3), int64(2), str(6)
memory usage: 1018.0 bytes
None

In [19]:
import pandas as pd
import numpy as np

# ১. একটি স্যাম্পল ডেটাফ্রেম তৈরি (আপনার ডেটার মতো)
data = {
    'Name': ['John', 'Akane', 'Doe'],
    'Score_Text': ['85', 'John', '90'], # এখানে মাঝখানে 'John' ভুল করে ঢুকেছে
    'Attendance': [10, 20, 30]
}
df = pd.DataFrame(data)

# ২. কলাম যোগ করার আগে ডেটা টাইপ ঠিক করা
# errors='coerce' দিলে 'John' এর মতো নামগুলো NaN (Not a Number) হয়ে যাবে
df['Score_Numeric'] = pd.to_numeric(df['Score_Text'], errors='coerce')

# ৩. নতুন কলাম যোগ করা (গাণিতিক হিসাবসহ)
# ধরা যাক, আমরা Score এবং Attendance যোগ করে একটি Total কলাম বানাচ্ছি
df['Total'] = df['Score_Numeric'] + df['Attendance']

# ৪. ফালতু বা NaN ভ্যালুগুলো ০ দিয়ে ভর্তি করা (ঐচ্ছিক)
df['Total'] = df['Total'].fillna(0)

print("--- আপডেট হওয়া ডেটাফ্রেম ---")
print(df)

--- আপডেট হওয়া ডেটাফ্রেম ---
    Name Score_Text  Attendance  Score_Numeric  Total
0   John         85          10           85.0   95.0
1  Akane       John          20            NaN    0.0
2    Doe         90          30           90.0  120.0

In [21]:
df['Score_Numeric']=pd.to_numeric(df['Score_Text'],errors='coerce')
df['Total']=df['Score_Numeric']+df['Attendance']
df['Total']=df['Total'].fillna(0)
print(df)

    Name Score_Text  Attendance  Score_Numeric  Total
0   John         85          10           85.0   95.0
1  Akane       John          20            NaN    0.0
2    Doe         90          30           90.0  120.0

In [25]:
numeric_arr = df.select_dtypes(include=['number']).to_numpy(dtype='float')
numeric_arr

array([[ 10.,  85.,  95.],
       [ 20.,  nan,   0.],
       [ 30.,  90., 120.]])

In [37]:
numeric_arr1=df2.select_dtypes(include=["number"]).to_numpy(dtype="float64")
numeric_arr1

array([[1.00e+00, 2.80e+01, 5.50e+04, 2.45e+01, 2.00e+00],
       [2.00e+00, 3.40e+01, 6.20e+04, 2.21e+01, 1.00e+00],
       [3.00e+00, 4.50e+01, 7.00e+04, 2.78e+01, 3.00e+00],
       [4.00e+00, 2.90e+01, 5.80e+04, 2.34e+01, 0.00e+00],
       [5.00e+00, 3.80e+01, 6.50e+04, 2.82e+01,      nan],
       [6.00e+00, 3.10e+01, 6.00e+04, 2.19e+01, 2.00e+00],
       [7.00e+00, 4.20e+01, 7.20e+04, 2.65e+01, 1.00e+00],
       [8.00e+00, 3.60e+01,      nan, 2.49e+01, 2.00e+00],
       [9.00e+00, 3.90e+01, 6.80e+04, 2.91e+01, 3.00e+00],
       [1.00e+01, 3.30e+01, 6.10e+04, 2.30e+01, 1.00e+00]])

In [36]:
# শুধু নিউমেরিক কলামগুলোকে float array-তে রূপান্তর
numeric_arr = df2.select_dtypes(include=['number']).to_numpy(dtype='float')

In [30]:
#প্রতিটি column-এ কয়টি non-null মান আছে তা বের করো।
df1.count()

id            10
name          10
age           10
sex           10
salary         9
bmi           10
children       9
smoker        10
region        10
department    10
join_date     10
is_manager    10
dtype: int64

In [34]:
arr1=df2.select_dtypes(include=["number"])
arr2=arr1.mean()
arr2

id              5.500000
age            35.500000
salary      63444.444444
bmi            25.140000
children        1.666667
dtype: float64

In [35]:
arr1=df2.select_dtypes(include=["number"])
arr2=arr1.max()
arr2

id             10.0
age            45.0
salary      72000.0
bmi            29.1
children        3.0
dtype: float64

In [40]:
arr3=df2.select_dtypes(include=["number"])
arr4=arr3.min()
arr4

id              1.0
age            28.0
salary      55000.0
bmi            21.9
children        0.0
dtype: float64

In [43]:
df2["salary"].mean()

np.float64(63444.444444444445)

In [47]:
df2["age"].max()

np.int64(45)

In [48]:
df2["salary"].min()

np.float64(55000.0)

In [51]:
df2[["salary","age"]]

    salary  age
0  55000.0   28
1  62000.0   34
2  70000.0   45
3  58000.0   29
4  65000.0   38
5  60000.0   31
6  72000.0   42
7      NaN   36
8  68000.0   39
9  61000.0   33

In [52]:
df2.columns

Index(['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker',
       'region', 'department', 'join_date', 'is_manager'],
      dtype='str')

In [53]:
print(list(df2.columns))

['id', 'name', 'age', 'sex', 'salary', 'bmi', 'children', 'smoker', 'region', 'department', 'join_date', 'is_manager']

In [55]:
#“Salary” column-এর সর্বনিম্ন, সর্বোচ্চ এবং median বের করো।
df2["salary"].mean()

np.float64(63444.444444444445)

In [56]:
df2["salary"].median()

np.float64(62000.0)

In [57]:
#DataFrame-এর প্রথম ৪টি row এবং শেষ ২টি row একসাথে প্রদর্শন করো।
ar1=df2.head(4)
ar2=df2.tail(2)
ar3=pd.concat([ar1,ar2],ignore_index=True)
ar3

,id,name,age,sex,salary,bmi,children,smoker,region,department,join_date,is_manager
0,1,John,28,M,55000.0,24.5,2.0,Yes,North,Sales,2020-01-15,False
1,2,Jane,34,F,62000.0,22.1,1.0,No,South,Marketing,2019-06-23,True
2,3,Bob,45,M,70000.0,27.8,3.0,Yes,East,IT,2015-09-10,False
3,4,Alice,29,F,58000.0,23.4,0.0,No,West,HR,2021-03-12,False
4,9,Tom,39,M,68000.0,29.1,3.0,Yes,North,Finance,2015-05-14,False
5,10,Susan,33,F,61000.0,23.0,1.0,No,South,HR,2019-08-25,False

In [61]:
print(df2["salary"].nunique())

9