In [1]:
import pandas as pd

In [2]:
import pandas as pd
df=pd.read_csv("insurance (1).csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
dic={
    "name":["maruf","nadia","sadia","saima"],
    "roll":[1,2,3,4],
    "age":[12,33,44,56],
    "dep":['cst','et','cst','sst']

}
dic=pd.DataFrame(dic)
dic

    name  roll  age  dep
0  maruf     1   12  cst
1  nadia     2   33   et
2  sadia     3   44  cst
3  saima     4   56  sst

In [4]:
import pandas as pd
d=[1,2,3]
df=pd.Series(d)

df

0    1
1    2
2    3
dtype: int64

In [5]:
df.info()

<class 'pandas.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 152.0 bytes

In [6]:
import numpy as np
data= np.random.rand(10,5)
data

array([[0.8857005 , 0.32013086, 0.40275079, 0.92861176, 0.05884044],
       [0.66266539, 0.42017256, 0.81001397, 0.53547617, 0.384033  ],
       [0.94175449, 0.64369   , 0.43929483, 0.06118298, 0.79000519],
       [0.22834114, 0.98576201, 0.98115844, 0.03628332, 0.23811705],
       [0.26161211, 0.9986173 , 0.00195356, 0.99215101, 0.97910147],
       [0.15222851, 0.89434398, 0.6814879 , 0.98965437, 0.68094171],
       [0.02002815, 0.08746337, 0.10474512, 0.11772519, 0.38870787],
       [0.75355985, 0.52088666, 0.838866  , 0.38781458, 0.55487917],
       [0.29557411, 0.21939174, 0.4627464 , 0.77460942, 0.62880921],
       [0.8357797 , 0.60961096, 0.76102566, 0.09429662, 0.97250168]])

In [7]:
import numpy as np
import pandas as pd
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    nan_value = np.random.choice(6,4, replace=False)
    data[nan_value, x] = np.nan
    daf = pd.DataFrame(data)
print(daf)

          0         1         2         3         4
0  0.084375       NaN       NaN       NaN       NaN
1       NaN       NaN  0.962777       NaN  0.143739
2  0.878499       NaN  0.329021  0.546769       NaN
3       NaN       NaN       NaN       NaN       NaN
4       NaN  0.768096       NaN       NaN  0.672869
5       NaN  0.924783       NaN  0.445800       NaN
6  0.713832  0.385751  0.338942  0.899619  0.997733
7  0.547124  0.436884  0.522475  0.160465  0.144702
8  0.286708  0.763748  0.055391  0.609841  0.440477
9  0.280360  0.484194  0.205203  0.134967  0.172805

In [8]:
daf.columns=['col1','col2','col3','col4', 'col5']
print(daf)

       col1      col2      col3      col4      col5
0  0.084375       NaN       NaN       NaN       NaN
1       NaN       NaN  0.962777       NaN  0.143739
2  0.878499       NaN  0.329021  0.546769       NaN
3       NaN       NaN       NaN       NaN       NaN
4       NaN  0.768096       NaN       NaN  0.672869
5       NaN  0.924783       NaN  0.445800       NaN
6  0.713832  0.385751  0.338942  0.899619  0.997733
7  0.547124  0.436884  0.522475  0.160465  0.144702
8  0.286708  0.763748  0.055391  0.609841  0.440477
9  0.280360  0.484194  0.205203  0.134967  0.172805

In [9]:
daf.columns=['col1','col2','col3','col4','col5']
print(daf)

       col1      col2      col3      col4      col5
0  0.084375       NaN       NaN       NaN       NaN
1       NaN       NaN  0.962777       NaN  0.143739
2  0.878499       NaN  0.329021  0.546769       NaN
3       NaN       NaN       NaN       NaN       NaN
4       NaN  0.768096       NaN       NaN  0.672869
5       NaN  0.924783       NaN  0.445800       NaN
6  0.713832  0.385751  0.338942  0.899619  0.997733
7  0.547124  0.436884  0.522475  0.160465  0.144702
8  0.286708  0.763748  0.055391  0.609841  0.440477
9  0.280360  0.484194  0.205203  0.134967  0.172805

In [11]:
daf1=daf.copy()
daf2=daf.copy()
daf3=daf.copy()
daf4=daf.copy()

In [ ]:
daf.dropna()

       col1      col2      col3      col4      col5
6  0.243104  0.287072  0.441736  0.828474  0.453872
7  0.128864  0.164502  0.237236  0.005123  0.692364
8  0.099246  0.567216  0.045920  0.766298  0.298950
9  0.245817  0.266267  0.995561  0.222057  0.419980

In [ ]:
daf.drop(['col5'],axis=1,inplace=True)
daf

       col1      col2      col3      col4
0       NaN       NaN  0.522416       NaN
1       NaN  0.270402       NaN       NaN
2       NaN       NaN       NaN       NaN
3       NaN       NaN       NaN  0.765276
4  0.761064       NaN       NaN       NaN
5  0.925338  0.253606  0.583349  0.364767
6  0.243104  0.287072  0.441736  0.828474
7  0.128864  0.164502  0.237236  0.005123
8  0.099246  0.567216  0.045920  0.766298
9  0.245817  0.266267  0.995561  0.222057

In [ ]:
daf.drop(['col4'],axis=1)

       col1      col3
0       NaN  0.522416
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4  0.761064       NaN
5  0.925338  0.583349
6  0.243104  0.441736
7  0.128864  0.237236
8  0.099246  0.045920
9  0.245817  0.995561

In [ ]:
daf

       col1      col3      col4
0       NaN  0.522416       NaN
1       NaN       NaN       NaN
2       NaN       NaN       NaN
3       NaN       NaN  0.765276
4  0.761064       NaN       NaN
5  0.925338  0.583349  0.364767
6  0.243104  0.441736  0.828474
7  0.128864  0.237236  0.005123
8  0.099246  0.045920  0.766298
9  0.245817  0.995561  0.222057